/**
 * Datos de las 29 razas oficiales (plantillas), transcritas del reglamento
 * oficial 2025 (BB2025_crap_v1.pdf, págs. 160-188).
 *
 * Los nombres de habilidad se guardan en español tal como aparecen en el
 * manual; prisma/seedRaces.ts los resuelve a claves del catálogo (con
 * normalización + alias). Si un nombre no resuelve, el sembrado avisa.
 *
 * Atributos: ma/st como número; ag/pa/av como el número "para superar" (3 = 3+);
 * pa: null = no puede pasar ("–").
 */

export interface SeedPosition {
  name: string;
  tags: string[];
  max: number;
  min?: number;
  cost: number;
  ma: number;
  st: number;
  ag: number;
  pa: number | null;
  av: number;
  skills: string[];
  primary: string[]; // letras A/F/G/M/P/T
  secondary: string[];
}

export interface SeedRace {
  key: string;
  name: string;
  pageRef: number;
  leagues: string[];
  specialRules: string[];
  rerollCost: number;
  rerollMax: number;
  allowsApothecary: boolean;
  /** Nota de construcción de equipo no modelada en el esquema (ej. "elige 1 Grandullón"). */
  note?: string;
  positions: SeedPosition[];
}

export const RACES: SeedRace[] = [
  {
    key: "amazonas",
    name: "Amazonas",
    pageRef: 160,
    leagues: ["Superliga Lustriana"],
    specialRules: [],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Guerrera Águila", tags: ["Humano", "Línea"], max: 16, cost: 50000, ma: 6, st: 3, ag: 3, pa: 4, av: 8, skills: ["Esquivar"], primary: ["G"], secondary: ["A", "F"] },
      { name: "Guerrera Pitón", tags: ["Humano", "Lanzador"], max: 2, cost: 80000, ma: 6, st: 3, ag: 3, pa: 3, av: 8, skills: ["Atento al balón", "Esquivar", "Pasar", "Pase seguro"], primary: ["G", "P"], secondary: ["A", "F"] },
      { name: "Guerrera Piraña", tags: ["Humano", "Blitzer"], max: 2, cost: 90000, ma: 7, st: 3, ag: 3, pa: 4, av: 8, skills: ["Atacar y huir", "En pie de un salto", "Esquivar"], primary: ["A", "G"], secondary: ["F"] },
      { name: "Guerrera Jaguar", tags: ["Humano", "Defensor"], max: 2, cost: 110000, ma: 6, st: 4, ag: 3, pa: 4, av: 9, skills: ["Esquivar", "Romper defensas"], primary: ["G", "F"], secondary: ["A"] },
    ],
  },
  {
    key: "orcos-negros",
    name: "Orcos Negros",
    pageRef: 161,
    leagues: ["Reyerta en las Yermas"],
    specialRules: ["Brutales", "Sobornos y Corrupción"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Goblin Magullado", tags: ["Goblin", "Línea"], max: 16, cost: 45000, ma: 6, st: 2, ag: 3, pa: 4, av: 8, skills: ["Cabeza dura", "Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A", "T"], secondary: ["F", "G", "P"] },
      { name: "Orco negro", tags: ["Orco", "Defensor"], max: 6, cost: 90000, ma: 4, st: 4, ag: 4, pa: 5, av: 10, skills: ["Apartar", "Luchador"], primary: ["F", "G"], secondary: ["A", "T"] },
      { name: "Troll Entrenado", tags: ["Troll", "Grandullón"], max: 1, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10, skills: ["Golpe mortífero", "Lanzar compañero", "Proyectil de vómito", "Realmente estúpido", "Regeneración", "Siempre hambriento"], primary: ["F"], secondary: ["A", "G", "P"] },
    ],
  },
  {
    key: "bretonianos",
    name: "Bretonianos",
    pageRef: 162,
    leagues: ["Clásica del Viejo Mundo"],
    specialRules: [],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Escudero Bretoniano", tags: ["Humano", "Línea"], max: 16, cost: 50000, ma: 6, st: 3, ag: 3, pa: 4, av: 8, skills: ["Forcejear"], primary: ["G"], secondary: ["A", "F"] },
      { name: "Caballero Bretoniano Receptor", tags: ["Humano", "Receptor"], max: 2, cost: 85000, ma: 7, st: 3, ag: 3, pa: 4, av: 9, skills: ["Agallas", "Atrapar", "Nervios de acero"], primary: ["G", "P"], secondary: ["A", "F"] },
      { name: "Caballero Bretoniano Lanzador", tags: ["Humano", "Lanzador"], max: 2, cost: 80000, ma: 6, st: 3, ag: 3, pa: 3, av: 9, skills: ["Agallas", "Nervios de acero", "Pasar"], primary: ["G", "P"], secondary: ["A", "F"] },
      { name: "Caballero del Grial", tags: ["Humano", "Blitzer"], max: 2, cost: 95000, ma: 7, st: 3, ag: 3, pa: 4, av: 10, skills: ["Agallas", "Equilibrio firme", "Placar"], primary: ["G", "F"], secondary: ["A"] },
    ],
  },
  {
    key: "elegidos-del-caos",
    name: "Elegidos del Caos",
    pageRef: 163,
    leagues: ["Competición del Caos"],
    specialRules: ["Elegidos de (elegir cualquier alineamiento)"],
    rerollCost: 50000,
    rerollMax: 8,
    allowsApothecary: true,
    note: "Puede tener un único jugador Grandullón, a elegir entre Troll, Ogro o Minotauro.",
    positions: [
      { name: "Línea Hombre Bestia", tags: ["Hombre Bestia", "Línea"], max: 16, cost: 55000, ma: 6, st: 3, ag: 3, pa: 3, av: 9, skills: ["Cabeza dura", "Cuernos"], primary: ["G", "M"], secondary: ["A", "F", "P", "T"] },
      { name: "Chaos Chosen", tags: ["Humano", "Defensor"], max: 4, cost: 100000, ma: 5, st: 4, ag: 3, pa: 5, av: 10, skills: ["Llave de brazo"], primary: ["F", "G", "M"], secondary: ["A", "T"] },
      { name: "Troll", tags: ["Troll", "Grandullón"], max: 1, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10, skills: ["Golpe mortífero", "Lanzar compañero", "Proyectil de vómito", "Realmente estúpido", "Regeneración", "Siempre hambriento", "Solitario (4+)"], primary: ["F", "M"], secondary: ["A", "G", "P"] },
      { name: "Ogro", tags: ["Ogro", "Grandullón"], max: 1, cost: 140000, ma: 5, st: 5, ag: 4, pa: 4, av: 10, skills: ["Cabeza dura", "Estúpido", "Golpe mortífero", "Lanzar compañero", "Solitario (4+)"], primary: ["F", "M"], secondary: ["A", "G"] },
      { name: "Minotauro", tags: ["Minotauro", "Grandullón"], max: 1, cost: 150000, ma: 5, st: 5, ag: 4, pa: 6, av: 9, skills: ["Cabeza dura", "Cuernos", "Furia", "Golpe mortífero", "Ira descontrolada", "Solitario (4+)"], primary: ["F", "M"], secondary: ["A", "G"] },
    ],
  },
  {
    key: "enanos-del-caos",
    name: "Enanos del Caos",
    pageRef: 164,
    leagues: ["Competición del Caos", "Reyerta en las Yermas"],
    specialRules: ["Elegidos de Hashut"],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Hobgoblin", tags: ["Goblin", "Línea"], max: 16, cost: 40000, ma: 6, st: 3, ag: 3, pa: 4, av: 8, skills: [], primary: ["T"], secondary: ["A", "F", "G"] },
      { name: "Asesino furtivo", tags: ["Goblin", "Especial"], max: 2, cost: 60000, ma: 6, st: 3, ag: 3, pa: 4, av: 8, skills: ["Apuñalar", "Perseguir"], primary: ["G", "T"], secondary: ["A", "M", "T"] },
      { name: "Defensor Enano del Caos", tags: ["Enano", "Defensor"], max: 4, cost: 70000, ma: 4, st: 3, ag: 4, pa: 6, av: 10, skills: ["Cabeza dura", "Piel férrea", "Placar"], primary: ["F", "G"], secondary: ["A", "M", "T"] },
      { name: "Forjador de llamas", tags: ["Enano", "Especial"], max: 2, cost: 80000, ma: 5, st: 3, ag: 4, pa: 6, av: 10, skills: ["Cabeza dura", "Exhalar fuego", "Luchador", "Presencia perturbadora"], primary: ["G", "F"], secondary: ["A", "M", "T"] },
      { name: "Centauro Toro", tags: ["Enano", "Blitzer"], max: 2, cost: 130000, ma: 6, st: 4, ag: 4, pa: 6, av: 10, skills: ["Cabeza dura", "Esprintar", "Pies firmes", "Tembloroso"], primary: ["F", "G"], secondary: ["A", "M", "T"] },
      { name: "Minotauro", tags: ["Minotauro", "Grandullón"], max: 1, cost: 150000, ma: 5, st: 5, ag: 4, pa: 6, av: 9, skills: ["Cabeza dura", "Cuernos", "Furia", "Golpe mortífero", "Ira descontrolada", "Solitario (4+)"], primary: ["F", "M"], secondary: ["A", "G"] },
    ],
  },
  {
    key: "renegados-del-caos",
    name: "Renegados del Caos",
    pageRef: 165,
    leagues: ["Competición del Caos"],
    specialRules: ["Elegidos de (elegir entre Khorne, Nurgle, Slaanesh, Tzeentch y Caos Absoluto)"],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: true,
    note: "Puede tener un único jugador Grandullón, a elegir entre Troll, Ogro, Minotauro o Rata Ogro.",
    positions: [
      { name: "Línea Renegado", tags: ["Humano", "Línea"], max: 16, cost: 50000, ma: 6, st: 3, ag: 3, pa: 4, av: 9, skills: ["Animosidad (todos)"], primary: ["G", "M", "T"], secondary: ["A", "F"] },
      { name: "Goblin Renegado", tags: ["Goblin", "Línea"], max: 1, cost: 40000, ma: 6, st: 2, ag: 3, pa: 4, av: 8, skills: ["Animosidad (todos)", "Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A", "M", "T"], secondary: ["G", "P"] },
      { name: "Orco Renegado", tags: ["Orco", "Línea"], max: 1, cost: 50000, ma: 5, st: 3, ag: 3, pa: 4, av: 10, skills: ["Animosidad (todos)"], primary: ["G", "M", "T"], secondary: ["A", "F"] },
      { name: "Skaven Renegado", tags: ["Skaven", "Línea"], max: 1, cost: 50000, ma: 7, st: 3, ag: 3, pa: 4, av: 8, skills: ["Animosidad (todos)"], primary: ["G", "M", "T"], secondary: ["A", "F"] },
      { name: "Elfo oscuro Renegado", tags: ["Elfo", "Línea"], max: 1, cost: 65000, ma: 6, st: 3, ag: 2, pa: 3, av: 9, skills: ["Animosidad (todos)"], primary: ["A", "G", "M", "T"], secondary: ["F"] },
      { name: "Humano Lanzador Renegado", tags: ["Humano", "Lanzador"], max: 1, cost: 75000, ma: 6, st: 3, ag: 3, pa: 3, av: 9, skills: ["Animosidad (todos)", "Manos seguras", "Pasar"], primary: ["G", "P", "M", "T"], secondary: ["A", "F"] },
      { name: "Troll", tags: ["Troll", "Grandullón"], max: 1, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10, skills: ["Golpe mortífero", "Lanzar compañero", "Proyectil de vómito", "Realmente estúpido", "Regeneración", "Siempre hambriento", "Solitario (4+)"], primary: ["F"], secondary: ["A", "M", "P", "G"] },
      { name: "Ogro", tags: ["Ogro", "Grandullón"], max: 1, cost: 140000, ma: 5, st: 5, ag: 4, pa: 5, av: 10, skills: ["Cabeza dura", "Estúpido", "Golpe mortífero", "Lanzar compañero", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G", "M"] },
      { name: "Minotauro", tags: ["Minotauro", "Grandullón"], max: 1, cost: 150000, ma: 5, st: 5, ag: 4, pa: 6, av: 9, skills: ["Cabeza dura", "Cuernos", "Furia", "Golpe mortífero", "Ira descontrolada", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G", "M"] },
      { name: "Rata Ogro", tags: ["Skaven", "Grandullón"], max: 1, cost: 150000, ma: 6, st: 5, ag: 4, pa: 6, av: 9, skills: ["Cola prensil", "Ferocidad animal", "Furia", "Golpe mortífero", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G", "M"] },
    ],
  },
  {
    key: "elfos-oscuros",
    name: "Elfos Oscuros",
    pageRef: 166,
    leagues: ["Ligas de los Reinos Élficos"],
    specialRules: [],
    rerollCost: 50000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Elfo Oscuro", tags: ["Elfo", "Línea"], max: 16, cost: 65000, ma: 6, st: 3, ag: 2, pa: 3, av: 9, skills: [], primary: ["A", "G"], secondary: ["F", "T"] },
      { name: "Corredor Elfo Oscuro", tags: ["Elfo", "Corredor"], max: 2, cost: 80000, ma: 7, st: 3, ag: 2, pa: 3, av: 8, skills: ["Pase precipitado", "Patada de despeje"], primary: ["A", "G", "P"], secondary: ["F", "T"] },
      { name: "Asesino Elfo Oscuro", tags: ["Elfo", "Especial"], max: 2, cost: 90000, ma: 7, st: 3, ag: 2, pa: 4, av: 8, skills: ["Apuñalar", "Atacar y huir", "Perseguir"], primary: ["A", "T"], secondary: ["F", "G"] },
      { name: "Blitzer Elfo Oscuro", tags: ["Elfo", "Blitzer"], max: 2, cost: 105000, ma: 7, st: 3, ag: 2, pa: 3, av: 9, skills: ["Placar"], primary: ["A", "G"], secondary: ["F", "P", "T"] },
      { name: "Elfa Bruja", tags: ["Elfo", "Especial"], max: 2, cost: 110000, ma: 7, st: 3, ag: 2, pa: 4, av: 8, skills: ["En pie de un salto", "Esquivar", "Furia"], primary: ["A", "G"], secondary: ["F", "T"] },
    ],
  },
  {
    key: "enanos",
    name: "Enanos",
    pageRef: 167,
    leagues: ["Superliga del Fin del Mundo"],
    specialRules: ["Brutos Brutales", "Sobornos y Corrupción"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Enano", tags: ["Enano", "Línea"], max: 16, cost: 70000, ma: 4, st: 3, ag: 4, pa: 5, av: 10, skills: ["Cabeza dura", "Placar", "Romper defensas"], primary: ["G", "T"], secondary: ["F"] },
      { name: "Corredor Enano", tags: ["Enano", "Corredor"], max: 2, cost: 80000, ma: 6, st: 3, ag: 3, pa: 4, av: 9, skills: ["Cabeza dura", "Esprintar", "Manos seguras"], primary: ["G", "P"], secondary: ["F"] },
      { name: "Blitzer Enano", tags: ["Enano", "Blitzer"], max: 2, cost: 100000, ma: 5, st: 3, ag: 4, pa: 4, av: 10, skills: ["Cabeza dura", "Placaje defensivo", "Placaje heroico", "Placar"], primary: ["F", "G"], secondary: ["P"] },
      { name: "Matatrolls", tags: ["Enano", "Especial"], max: 2, cost: 95000, ma: 5, st: 3, ag: 4, pa: 5, av: 9, skills: ["Agallas", "Cabeza dura", "Furia", "Odio (Troll)", "Placar"], primary: ["F", "G"], secondary: ["T"] },
      { name: "Apisonadora", tags: ["Enano", "Grandullón", "Especial"], max: 1, cost: 170000, ma: 5, st: 7, ag: 5, pa: null, av: 11, skills: ["Abrirse paso", "Arma secreta", "El balón ni verlo", "Golpe mortífero", "Imparable", "Jugar sucio", "Mantenerse firme", "Solitario (4+)"], primary: ["F", "T"], secondary: ["G"] },
    ],
  },
  {
    key: "union-elfica",
    name: "Unión Élfica",
    pageRef: 168,
    leagues: ["Liga de los Reinos Élficos"],
    specialRules: [],
    rerollCost: 50000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Elfo", tags: ["Elfo", "Línea"], max: 16, cost: 65000, ma: 6, st: 3, ag: 2, pa: 3, av: 8, skills: ["Dejada"], primary: ["A", "G"], secondary: ["F"] },
      { name: "Lanzador Elfo", tags: ["Elfo", "Lanzador"], max: 2, cost: 75000, ma: 6, st: 3, ag: 2, pa: 2, av: 8, skills: ["Pasar", "Pase a lo loco"], primary: ["A", "G", "P"], secondary: ["F"] },
      { name: "Receptor Elfo", tags: ["Elfo", "Receptor"], max: 2, cost: 100000, ma: 8, st: 3, ag: 2, pa: 4, av: 8, skills: ["Atrapar", "Nervios de acero", "Recepción heroica"], primary: ["A", "G"], secondary: ["F"] },
      { name: "Blitzer Elfo", tags: ["Elfo", "Blitzer"], max: 2, cost: 115000, ma: 7, st: 3, ag: 2, pa: 3, av: 9, skills: ["Echarse a un lado", "Placar"], primary: ["A", "G"], secondary: ["F", "P"] },
    ],
  },
  {
    key: "gnomos",
    name: "Gnomos",
    pageRef: 169,
    leagues: ["Copa Dedal Halfling", "Liga de los Bosques"],
    specialRules: [],
    rerollCost: 50000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Gnomo", tags: ["Gnomo", "Línea"], max: 16, cost: 40000, ma: 5, st: 2, ag: 3, pa: 4, av: 7, skills: ["En pie de un salto", "Escurridizo", "Forcejear", "Humanoide bala"], primary: ["A"], secondary: ["F", "G", "T"] },
      { name: "Zorro de los bosques", tags: ["Animal", "Corredor"], max: 2, cost: 50000, ma: 7, st: 2, ag: 2, pa: null, av: 6, skills: ["Echarse a un lado", "El balón es mío", "Escurridizo", "Esquivar"], primary: [], secondary: ["A"] },
      { name: "Ilusionista Gnomo", tags: ["Gnomo", "Especial"], max: 2, cost: 50000, ma: 5, st: 2, ag: 3, pa: 3, av: 7, skills: ["Embustero", "En pie de un salto", "Escurridizo", "Forcejear"], primary: ["A"], secondary: ["F", "G", "T"] },
      { name: "Señor de las bestias Gnomo", tags: ["Gnomo", "Defensor"], max: 2, cost: 55000, ma: 5, st: 2, ag: 3, pa: 4, av: 8, skills: ["Defensa", "En pie de un salto", "Escurridizo", "Forcejear"], primary: ["A"], secondary: ["F", "G", "T"] },
      { name: "Hombre árbol del Bosque Altern", tags: ["Hombre árbol", "Grandullón"], max: 2, cost: 120000, ma: 2, st: 6, ag: 5, pa: 5, av: 11, skills: ["Brazo fuerte", "Cabeza dura", "Echar raíces", "Golpe mortífero", "Lanzar compañero", "Mantenerse firme", "¡Tronco va!"], primary: ["F"], secondary: ["A", "G", "P"] },
    ],
  },
  {
    key: "goblins",
    name: "Goblins",
    pageRef: 170,
    leagues: ["Reyerta en las Yermas", "Reto del Inframundo"],
    specialRules: ["Sobornos y Corrupción"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Goblin", tags: ["Goblin", "Línea"], max: 16, cost: 40000, ma: 6, st: 2, ag: 3, pa: 4, av: 8, skills: ["Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A", "T"], secondary: ["G", "F", "P"] },
      { name: "Loony", tags: ["Goblin", "Especial"], max: 1, cost: 40000, ma: 6, st: 2, ag: 3, pa: null, av: 8, skills: ["Arma secreta", "Escurridizo", "El balón ni verlo", "Motosierra"], primary: ["T"], secondary: ["A", "F", "G"] },
      { name: "Booma", tags: ["Goblin", "Especial"], max: 1, cost: 45000, ma: 6, st: 2, ag: 3, pa: 4, av: 8, skills: ["Arma secreta", "Bombardero", "Escurridizo", "Esquivar"], primary: ["P", "T"], secondary: ["A", "F", "G"] },
      { name: "'Ooligan", tags: ["Goblin", "Especial"], max: 1, cost: 60000, ma: 6, st: 2, ag: 3, pa: 5, av: 8, skills: ["Escurridizo", "Esquivar", "Humanoide bala", "Jugar sucio", "Presencia perturbadora", "Provocar"], primary: ["A", "T"], secondary: ["F", "G"] },
      { name: "Doom Diver", tags: ["Goblin", "Especial"], max: 1, cost: 65000, ma: 6, st: 2, ag: 3, pa: 6, av: 8, skills: ["Escurridizo", "Esquivar", "Humanoide bala", "Planear"], primary: ["A"], secondary: ["F", "G", "T"] },
      { name: "Fanático", tags: ["Goblin", "Especial"], max: 1, cost: 70000, ma: 3, st: 7, ag: 3, pa: null, av: 8, skills: ["Arma secreta", "Bola con cadena", "El balón ni verlo", "Escurridizo"], primary: ["F", "T"], secondary: ["A", "G"] },
      { name: "Pogo saltarín", tags: ["Goblin", "Especial"], max: 1, cost: 75000, ma: 7, st: 2, ag: 3, pa: 4, av: 8, skills: ["Escurridizo", "Esquivar", "Pogo saltarín"], primary: ["A"], secondary: ["F", "G", "T"] },
      { name: "Troll entrenado", tags: ["Troll", "Grandullón"], max: 2, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10, skills: ["Golpe mortífero", "Lanzar compañero", "Proyectil de vómito", "Realmente estúpido", "Regeneración", "Siempre hambriento"], primary: ["F"], secondary: ["A", "G", "P"] },
    ],
  },
  {
    key: "halflings",
    name: "Halflings",
    pageRef: 171,
    leagues: ["Copa Dedal Halfling", "Liga de los Bosques"],
    specialRules: [],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Halfling Esperanzado", tags: ["Halfling", "Línea"], max: 16, cost: 30000, ma: 5, st: 2, ag: 3, pa: 4, av: 7, skills: ["Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A"], secondary: ["F", "G", "T"] },
      { name: "Halfling Forzudo", tags: ["Halfling", "Defensor"], max: 2, cost: 50000, ma: 5, st: 2, ag: 3, pa: 3, av: 8, skills: ["Escurridizo", "Esquivar", "Zafarse"], primary: ["A", "P"], secondary: ["F", "G", "T"] },
      { name: "Receptor Halfling", tags: ["Halfling", "Receptor"], max: 2, cost: 55000, ma: 5, st: 2, ag: 3, pa: 4, av: 7, skills: ["Atrapar", "Escurridizo", "Esprintar", "Esquivar", "Humanoide bala"], primary: ["A"], secondary: ["F", "G", "T"] },
      { name: "Hombre árbol del Bosque Altern", tags: ["Hombre árbol", "Grandullón"], max: 2, cost: 120000, ma: 2, st: 6, ag: 5, pa: 5, av: 11, skills: ["Brazo fuerte", "Cabeza dura", "Echar raíces", "Golpe mortífero", "Lanzar compañero", "Mantenerse firme", "¡Tronco va!"], primary: ["F"], secondary: ["A", "G", "P"] },
    ],
  },
  {
    key: "humanos",
    name: "Humanos",
    pageRef: 172,
    leagues: ["Clásica del Viejo Mundo"],
    specialRules: ["Capitán del Equipo"],
    rerollCost: 50000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Humano", tags: ["Humano", "Línea"], max: 16, cost: 50000, ma: 6, st: 3, ag: 3, pa: 4, av: 9, skills: [], primary: ["G"], secondary: ["A", "F", "T"] },
      { name: "Halfling Esperanzado", tags: ["Halfling", "Línea"], max: 3, cost: 30000, ma: 5, st: 2, ag: 3, pa: 4, av: 7, skills: ["Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A"], secondary: ["F", "G", "T"] },
      { name: "Receptor Humano", tags: ["Humano", "Receptor"], max: 2, cost: 75000, ma: 8, st: 3, ag: 3, pa: 4, av: 8, skills: ["Atrapar", "Esquivar"], primary: ["A", "G"], secondary: ["F", "P", "T"] },
      { name: "Lanzador Humano", tags: ["Humano", "Lanzador"], max: 2, cost: 75000, ma: 6, st: 3, ag: 3, pa: 3, av: 9, skills: ["Manos seguras", "Pasar"], primary: ["G", "P"], secondary: ["A", "F", "T"] },
      { name: "Blitzer Humano", tags: ["Humano", "Blitzer"], max: 2, cost: 85000, ma: 7, st: 3, ag: 3, pa: 4, av: 9, skills: ["Placaje defensivo", "Placar"], primary: ["F", "G"], secondary: ["A", "T"] },
      { name: "Ogro", tags: ["Ogro", "Grandullón"], max: 1, cost: 140000, ma: 5, st: 5, ag: 4, pa: 5, av: 10, skills: ["Cabeza dura", "Estúpido", "Golpe mortífero", "Lanzar compañero", "Solitario (3+)"], primary: ["F"], secondary: ["A", "G", "M"] },
    ],
  },
  {
    key: "nobles-imperiales",
    name: "Nobles Imperiales",
    pageRef: 173,
    leagues: ["Clásica del Viejo Mundo"],
    specialRules: [],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Séquito imperial", tags: ["Humano", "Línea"], max: 16, cost: 45000, ma: 6, st: 3, ag: 3, pa: 4, av: 8, skills: ["Zafarse"], primary: ["G"], secondary: ["A", "F"] },
      { name: "Lanzador Imperial", tags: ["Humano", "Lanzador"], max: 2, cost: 75000, ma: 6, st: 3, ag: 3, pa: 2, av: 9, skills: ["Pasar", "Pasar y seguir", "Profesional"], primary: ["G", "F"], secondary: ["A", "F"] },
      { name: "Guardaespaldas", tags: ["Humano", "Defensor"], max: 2, cost: 85000, ma: 5, st: 3, ag: 3, pa: 4, av: 9, skills: ["Forcejear", "Mantenerse firme"], primary: ["F", "G"], secondary: ["A"] },
      { name: "Blitzer Noble", tags: ["Humano", "Blitzer"], max: 2, cost: 90000, ma: 7, st: 3, ag: 3, pa: 4, av: 9, skills: ["Atrapar", "Placar", "Profesional"], primary: ["A", "G"], secondary: ["F", "P"] },
      { name: "Ogro", tags: ["Ogro", "Grandullón"], max: 1, cost: 140000, ma: 5, st: 5, ag: 4, pa: 5, av: 10, skills: ["Cabeza dura", "Estúpido", "Golpe mortífero", "Lanzar compañero", "Solitario (3+)"], primary: ["F"], secondary: ["A", "G", "M"] },
    ],
  },
  {
    key: "khorne",
    name: "Khorne",
    pageRef: 174,
    leagues: ["Competición del Caos"],
    specialRules: ["Brutos Brutales", "Elegidos de Khorne"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Merodeador de la Sangre", tags: ["Humano", "Línea"], max: 16, cost: 50000, ma: 6, st: 3, ag: 3, pa: 4, av: 8, skills: ["Furia asesina"], primary: ["G", "M"], secondary: ["A", "F", "T"] },
      { name: "Khorngor", tags: ["Hombre bestia", "Corredor"], max: 2, cost: 70000, ma: 6, st: 3, ag: 3, pa: 4, av: 9, skills: ["Cabeza dura", "Cuernos", "En pie de un salto", "Imparable"], primary: ["F", "G", "M"], secondary: ["A", "P", "T"] },
      { name: "Buscasangres", tags: ["Humano", "Receptor"], max: 4, cost: 105000, ma: 5, st: 4, ag: 4, pa: 6, av: 10, skills: ["Furia asesina"], primary: ["F", "G", "M"], secondary: ["A", "T"] },
      { name: "Engendro de sangre", tags: ["Engendro", "Grandullón"], max: 1, cost: 160000, ma: 5, st: 5, ag: 4, pa: 6, av: 9, skills: ["Furia", "Garras", "Golpe mortífero", "Ira descontrolada", "Solitario (4+)"], primary: ["F", "M"], secondary: ["A", "T"] },
    ],
  },
  {
    key: "hombres-lagarto",
    name: "Hombres Lagarto",
    pageRef: 175,
    leagues: ["Superliga Lustriana"],
    specialRules: [],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Eslizón Línea", tags: ["Hombre lagarto", "Línea"], max: 16, cost: 60000, ma: 8, st: 2, ag: 3, pa: 4, av: 8, skills: ["Escurridizo", "Esquivar"], primary: ["A"], secondary: ["F", "G", "P", "T"] },
      { name: "Eslizón Camaleón", tags: ["Hombre lagarto", "Lanzador"], max: 2, cost: 70000, ma: 8, st: 3, ag: 3, pa: 3, av: 8, skills: ["Atento al balón", "Escurridizo", "Esquivar", "Perseguir"], primary: ["A", "P"], secondary: ["F", "G", "T"] },
      { name: "Saurio defensor", tags: ["Hombre lagarto", "Defensor"], max: 6, cost: 90000, ma: 6, st: 4, ag: 5, pa: 6, av: 10, skills: ["Imparable", "Tembloroso"], primary: ["F", "G"], secondary: ["A"] },
      { name: "Kroxigor", tags: ["Hombre lagarto", "Grandullón"], max: 1, cost: 140000, ma: 6, st: 5, ag: 5, pa: 6, av: 10, skills: ["Cabeza dura", "Cola prensil", "Estúpido", "Golpe mortífero", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G"] },
    ],
  },
  {
    key: "horrores-nigromanticos",
    name: "Horrores Nigrománticos",
    pageRef: 176,
    leagues: ["Selectiva de Sylvania"],
    specialRules: ["Señores de los No Muertos"],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Zombi", tags: ["Humano", "No muerto", "Zombi", "Línea"], max: 16, cost: 40000, ma: 4, st: 3, ag: 4, pa: 6, av: 9, skills: ["Piquete de ojos", "Regeneración", "Tembloroso"], primary: ["G", "T"], secondary: ["A", "F"] },
      { name: "Corredor Necrófago", tags: ["Necrófago", "No muerto", "Corredor"], max: 2, cost: 75000, ma: 7, st: 3, ag: 3, pa: 3, av: 8, skills: ["Esquivar", "Regeneración"], primary: ["A", "G"], secondary: ["F", "P", "T"] },
      { name: "Espectro", tags: ["Espectro", "No muerto", "Defensor"], max: 2, cost: 85000, ma: 6, st: 3, ag: 3, pa: null, av: 9, skills: ["Apariencia asquerosa", "Echarse a un lado", "El balón ni verlo", "Placar", "Regeneración"], primary: ["F", "G"], secondary: ["A", "T"] },
      { name: "Golem de carne", tags: ["Constructo", "No muerto", "Defensor"], max: 2, cost: 110000, ma: 4, st: 4, ag: 4, pa: 6, av: 10, skills: ["Cabeza dura", "Mantenerse firme", "Regeneración", "Tembloroso"], primary: ["F", "G"], secondary: ["A", "T"] },
      { name: "Hombre lobo", tags: ["Hombre lobo", "No muerto", "Blitzer"], max: 2, cost: 120000, ma: 8, st: 3, ag: 3, pa: 3, av: 9, skills: ["Furia", "Garras", "Regeneración"], primary: ["A", "G"], secondary: ["F", "P", "T"] },
    ],
  },
  {
    key: "norses",
    name: "Norses",
    pageRef: 177,
    leagues: ["Clásica del Viejo Mundo", "Competición del Caos"],
    specialRules: ["Si elige Competición del Caos, el equipo gana Elegidos de Khorne"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Saqueador nórdico", tags: ["Humano", "Línea"], max: 16, cost: 50000, ma: 6, st: 3, ag: 3, pa: 4, av: 8, skills: ["Borracho", "Cabeza dura", "Placar", "Tembloroso"], primary: ["G"], secondary: ["A", "F", "P"] },
      { name: "Jabalí Cervecero", tags: ["Animal", "Especial"], max: 2, cost: 20000, ma: 5, st: 1, ag: 3, pa: null, av: 6, skills: ["Canijo", "El balón ni verlo", "Escurridizo", "Esquivar", "Levantar compañero"], primary: [], secondary: ["A"] },
      { name: "Berserker nórdico", tags: ["Humano", "Blitzer"], max: 2, cost: 90000, ma: 6, st: 3, ag: 3, pa: 5, av: 8, skills: ["En pie de un salto", "Furia", "Placar"], primary: ["F", "G"], secondary: ["A", "P"] },
      { name: "Valquiria", tags: ["Humano", "Receptor", "Lanzador"], max: 2, cost: 95000, ma: 7, st: 3, ag: 3, pa: 3, av: 8, skills: ["Agallas", "Atrapar", "Pasar", "Robar el balón"], primary: ["A", "G", "P"], secondary: ["F"] },
      { name: "Ulfwerner", tags: ["Humano", "Defensor"], max: 2, cost: 105000, ma: 6, st: 4, ag: 4, pa: 6, av: 9, skills: ["Furia", "Tembloroso"], primary: ["F", "G"], secondary: ["A"] },
      { name: "Yhetee", tags: ["Yhetee", "Grandullón"], max: 1, cost: 140000, ma: 5, st: 5, ag: 4, pa: 6, av: 9, skills: ["Furia", "Garras", "Ira descontrolada", "Presencia perturbadora", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G"] },
    ],
  },
  {
    key: "nurgle",
    name: "Nurgle",
    pageRef: 178,
    leagues: ["Competición del Caos"],
    specialRules: ["Brutos Brutales", "Elegidos de Nurgle"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: false,
    positions: [
      { name: "Línea Putrefacto", tags: ["Humano", "Línea"], max: 16, cost: 40000, ma: 5, st: 3, ag: 4, pa: 6, av: 9, skills: ["Descomposición", "Infectado"], primary: ["G", "M", "T"], secondary: ["A", "F"] },
      { name: "Pestigor", tags: ["Hombre bestia", "Corredor"], max: 2, cost: 70000, ma: 6, st: 3, ag: 3, pa: 4, av: 9, skills: ["Cabeza dura", "Cuernos", "Equilibrio firme", "Infectado", "Regeneración"], primary: ["F", "G", "M"], secondary: ["A", "P", "T"] },
      { name: "Hinchado", tags: ["Humano", "Defensor"], max: 4, cost: 110000, ma: 4, st: 4, ag: 4, pa: 6, av: 10, skills: ["Apariencia asquerosa", "Infectado", "Mantenerse firme", "Presencia perturbadora", "Regeneración", "Tembloroso"], primary: ["F", "G", "M"], secondary: ["A", "T"] },
      { name: "Engendro pútrido", tags: ["Engendro", "Grandullón"], max: 1, cost: 140000, ma: 4, st: 5, ag: 5, pa: 6, av: 10, skills: ["Apariencia asquerosa", "Golpe mortífero", "Infectado", "Levantar compañero", "Presencia perturbadora", "Realmente estúpido", "Regeneración", "Tentáculos", "Solitario (4+)"], primary: ["F"], secondary: ["G", "M", "T"] },
    ],
  },
  {
    key: "ogros",
    name: "Ogros",
    pageRef: 179,
    leagues: ["Reyerta en las Yermas", "Superliga del Fin del Mundo"],
    specialRules: ["Brutos Brutales", "Líneas Prescindibles"],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: false,
    positions: [
      { name: "Línea Gnoblar", tags: ["Gnoblar", "Línea"], max: 16, cost: 15000, ma: 5, st: 1, ag: 3, pa: 4, av: 6, skills: ["Canijo", "Echarse a un lado", "Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A", "T"], secondary: ["G"] },
      { name: "Defensor Ogro", tags: ["Ogro", "Defensor", "Grandullón"], max: 5, cost: 140000, ma: 5, st: 5, ag: 4, pa: 5, av: 10, skills: ["Cabeza dura", "Estúpido", "Golpe mortífero", "Lanzar compañero"], primary: ["F"], secondary: ["A", "G", "P", "T"] },
      { name: "Pateador Enano Ogro", tags: ["Ogro", "Lanzador", "Grandullón"], max: 1, cost: 145000, ma: 5, st: 5, ag: 4, pa: 4, av: 10, skills: ["Cabeza dura", "Chutar compañero", "Estúpido", "Golpe mortífero"], primary: ["F", "P"], secondary: ["A", "G", "T"] },
    ],
  },
  {
    key: "alianza-viejo-mundo",
    name: "Alianza del Viejo Mundo",
    pageRef: 180,
    leagues: ["Clásica del Viejo Mundo"],
    specialRules: [],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: true,
    note: "Puede tener un único jugador Grandullón, a elegir entre Ogro u Hombre árbol.",
    positions: [
      { name: "Línea Humano", tags: ["Humano", "Línea"], max: 16, cost: 50000, ma: 6, st: 3, ag: 3, pa: 4, av: 9, skills: [], primary: ["G"], secondary: ["A", "F"] },
      { name: "Halfling Esperanzado", tags: ["Halfling", "Línea"], max: 5, cost: 30000, ma: 5, st: 2, ag: 3, pa: 4, av: 7, skills: ["Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A"], secondary: ["F", "G"] },
      { name: "Receptor Humano", tags: ["Humano", "Receptor"], max: 1, cost: 75000, ma: 8, st: 3, ag: 3, pa: 4, av: 8, skills: ["Atrapar", "Esquivar"], primary: ["A", "G"], secondary: ["F", "P"] },
      { name: "Línea Enano", tags: ["Enano", "Línea"], max: 3, cost: 70000, ma: 4, st: 3, ag: 4, pa: 5, av: 10, skills: ["Cabeza dura", "Placar", "Romper defensas"], primary: ["G", "T"], secondary: ["F"] },
      { name: "Lanzador Humano", tags: ["Humano", "Lanzador"], max: 1, cost: 75000, ma: 6, st: 3, ag: 3, pa: 3, av: 9, skills: ["Manos seguras", "Pasar"], primary: ["G", "P"], secondary: ["A", "F"] },
      { name: "Corredor Enano", tags: ["Enano", "Corredor"], max: 1, cost: 80000, ma: 6, st: 3, ag: 3, pa: 4, av: 9, skills: ["Cabeza dura", "Esprintar", "Manos seguras"], primary: ["G", "P"], secondary: ["A", "F"] },
      { name: "Blitzer Humano", tags: ["Humano", "Blitzer"], max: 1, cost: 85000, ma: 7, st: 3, ag: 3, pa: 4, av: 9, skills: ["Placaje defensivo", "Placar"], primary: ["F", "G"], secondary: ["A"] },
      { name: "Blitzer Enano", tags: ["Enano", "Blitzer"], max: 1, cost: 100000, ma: 5, st: 3, ag: 4, pa: 4, av: 10, skills: ["Cabeza dura", "Placaje defensivo", "Placaje heroico", "Placar"], primary: ["F", "G"], secondary: ["P"] },
      { name: "Matatrolls", tags: ["Enano", "Especial"], max: 1, cost: 95000, ma: 5, st: 3, ag: 4, pa: 5, av: 9, skills: ["Agallas", "Cabeza dura", "Furia", "Odio (Troll)", "Placar"], primary: ["F", "G"], secondary: ["A"] },
      { name: "Ogro", tags: ["Ogro", "Grandullón"], max: 1, cost: 140000, ma: 5, st: 5, ag: 4, pa: 5, av: 10, skills: ["Cabeza dura", "Estúpido", "Golpe mortífero", "Lanzar compañero", "Solitario (3+)"], primary: ["F"], secondary: ["A", "G", "M"] },
      { name: "Hombre árbol del Bosque Altern", tags: ["Hombre árbol", "Grandullón"], max: 1, cost: 120000, ma: 2, st: 6, ag: 5, pa: 5, av: 11, skills: ["Brazo fuerte", "Cabeza dura", "Echar raíces", "Golpe mortífero", "Lanzar compañero", "Mantenerse firme", "¡Tronco va!"], primary: ["F"], secondary: ["A", "G", "P"] },
    ],
  },
  {
    key: "orcos",
    name: "Orcos",
    pageRef: 181,
    leagues: ["Reyerta en las Yermas"],
    specialRules: ["Brutos Brutales", "Capitán del Equipo"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Orco", tags: ["Orco", "Línea"], max: 16, cost: 50000, ma: 5, st: 3, ag: 3, pa: 4, av: 10, skills: [], primary: ["F", "G"], secondary: ["A", "T"] },
      { name: "Línea Goblin", tags: ["Goblin", "Línea"], max: 4, cost: 40000, ma: 6, st: 2, ag: 3, pa: 3, av: 8, skills: ["Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A", "T"], secondary: ["G", "F", "P"] },
      { name: "Lanzador Orco", tags: ["Orco", "Lanzador"], max: 2, cost: 75000, ma: 6, st: 3, ag: 3, pa: 3, av: 9, skills: ["Manos seguras", "Pasar"], primary: ["G", "P"], secondary: ["A", "F", "T"] },
      { name: "Blitzer Orco", tags: ["Orco", "Blitzer"], max: 2, cost: 85000, ma: 6, st: 3, ag: 3, pa: 4, av: 10, skills: ["Abrirse paso", "Placar"], primary: ["F", "G"], secondary: ["A", "T"] },
      { name: "Defensor Big Un", tags: ["Orco", "Defensor"], max: 2, cost: 95000, ma: 5, st: 4, ag: 4, pa: 6, av: 10, skills: ["Cabeza dura", "Golpe mortífero", "Provocar", "Tembloroso"], primary: ["F", "G"], secondary: ["A", "T"] },
      { name: "Troll", tags: ["Troll", "Grandullón"], max: 1, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10, skills: ["Golpe mortífero", "Lanzar compañero", "Proyectil de vómito", "Realmente estúpido", "Regeneración", "Siempre hambriento", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G", "P"] },
    ],
  },
  {
    key: "no-muertos",
    name: "No Muertos",
    pageRef: 182,
    leagues: ["Selectiva de Sylvania"],
    specialRules: ["Señores de los No Muertos"],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: false,
    positions: [
      { name: "Línea Esqueleto", tags: ["Humano", "Línea", "No muerto", "Esqueleto"], max: 16, cost: 40000, ma: 5, st: 3, ag: 4, pa: 6, av: 8, skills: ["Cabeza dura", "Regeneración"], primary: ["G"], secondary: ["A", "F", "T"] },
      { name: "Línea Zombi", tags: ["Humano", "Línea", "No muerto", "Zombi"], max: 16, cost: 40000, ma: 4, st: 3, ag: 4, pa: 6, av: 9, skills: ["Piquete de ojos", "Regeneración", "Tembloroso"], primary: ["G", "T"], secondary: ["A", "F"] },
      { name: "Corredor Necrófago", tags: ["Necrófago", "Corredor"], max: 2, cost: 75000, ma: 7, st: 3, ag: 3, pa: 3, av: 8, skills: ["Esquivar", "Regeneración"], primary: ["A", "G"], secondary: ["F", "P", "T"] },
      { name: "Blitzer Tumulario", tags: ["Humano", "Blitzer", "No muerto", "Esqueleto"], max: 2, cost: 95000, ma: 6, st: 3, ag: 3, pa: 5, av: 9, skills: ["Cabeza dura", "Placaje defensivo", "Placar", "Regeneración"], primary: ["F", "G"], secondary: ["A", "T"] },
      { name: "Momia", tags: ["Humano", "Defensor", "No muerto", "Grandullón"], max: 2, cost: 125000, ma: 3, st: 5, ag: 5, pa: 6, av: 10, skills: ["Golpe mortífero", "Regeneración"], primary: ["F", "G"], secondary: ["A"] },
    ],
  },
  {
    key: "skaven",
    name: "Skaven",
    pageRef: 183,
    leagues: ["Retos del Inframundo"],
    specialRules: [],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Guerrero de clan", tags: ["Skaven", "Línea"], max: 16, cost: 50000, ma: 7, st: 3, ag: 3, pa: 4, av: 8, skills: [], primary: ["G", "T"], secondary: ["A", "F", "M"] },
      { name: "Lanzador Skaven", tags: ["Skaven", "Lanzador"], max: 2, cost: 80000, ma: 7, st: 3, ag: 3, pa: 2, av: 8, skills: ["Manos seguras", "Pasar"], primary: ["G", "P"], secondary: ["A", "F", "M", "T"] },
      { name: "Corredor de alcantarillas", tags: ["Skaven", "Corredor"], max: 2, cost: 85000, ma: 9, st: 2, ag: 2, pa: 4, av: 8, skills: ["Apuñalar", "Esquivar"], primary: ["A", "G", "T"], secondary: ["F", "M"] },
      { name: "Blitzer Skaven", tags: ["Skaven", "Blitzer"], max: 2, cost: 90000, ma: 8, st: 3, ag: 3, pa: 4, av: 9, skills: ["Placar", "Robar el balón"], primary: ["F", "G"], secondary: ["A", "M", "T"] },
      { name: "Rata Ogro", tags: ["Skaven", "Grandullón"], max: 1, cost: 150000, ma: 6, st: 5, ag: 4, pa: 6, av: 9, skills: ["Cola prensil", "Ferocidad animal", "Furia", "Golpe mortífero", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G", "M"] },
    ],
  },
  {
    key: "snotlings",
    name: "Snotlings",
    pageRef: 184,
    leagues: ["Retos del Inframundo"],
    specialRules: ["Colar Jugadores", "Líneas Prescindibles", "Sobornos y Corrupción"],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Snotling", tags: ["Snotling", "Línea"], max: 16, cost: 15000, ma: 5, st: 1, ag: 3, pa: 4, av: 6, skills: ["Canijo", "Echarse a un lado", "Escurridizo", "Esquivar", "Humanoide bala", "Insignificante"], primary: ["A", "T"], secondary: ["G"] },
      { name: "Fun-hoppa", tags: ["Snotling", "Especial"], max: 2, cost: 20000, ma: 6, st: 1, ag: 3, pa: 4, av: 6, skills: ["Echarse a un lado", "Escurridizo", "Esquivar", "Humanoide bala", "Pogo saltarín"], primary: ["A", "T"], secondary: ["G"] },
      { name: "Stilty Runna", tags: ["Snotling", "Corredor"], max: 2, cost: 20000, ma: 6, st: 1, ag: 3, pa: 4, av: 6, skills: ["Echarse a un lado", "Escurridizo", "Esprintar", "Esquivar", "Humanoide bala"], primary: ["A", "T"], secondary: ["G"] },
      { name: "Fungus Flinga", tags: ["Snotling", "Especial"], max: 2, cost: 30000, ma: 5, st: 1, ag: 3, pa: 4, av: 6, skills: ["Arma secreta", "Bombardero", "Canijo", "Echarse a un lado", "Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A", "P", "T"], secondary: ["G"] },
      { name: "Vagoneta Snotling", tags: ["Snotling", "Especial", "Grandullón"], max: 2, cost: 100000, ma: 5, st: 5, ag: 5, pa: 6, av: 9, skills: ["Golpe mortífero", "Imparable", "Jugar sucio", "Mantenerse firme", "Realmente estúpido"], primary: ["F", "T"], secondary: ["A", "G"] },
      { name: "Troll entrenado", tags: ["Troll", "Grandullón"], max: 2, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10, skills: ["Golpe mortífero", "Lanzar compañero", "Proyectil de vómito", "Realmente estúpido", "Regeneración", "Siempre hambriento"], primary: ["F"], secondary: ["A", "G", "P"] },
    ],
  },
  {
    key: "reyes-tumularios",
    name: "Reyes Tumularios",
    pageRef: 185,
    leagues: ["Selectiva de Sylvania"],
    specialRules: ["Señores de los No Muertos"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: false,
    positions: [
      { name: "Línea Esqueleto", tags: ["Humano", "Línea", "No muerto", "Esqueleto"], max: 16, cost: 40000, ma: 5, st: 3, ag: 4, pa: 6, av: 8, skills: ["Cabeza dura", "Regeneración"], primary: ["G"], secondary: ["A", "F", "T"] },
      { name: "Lanzador de los Reyes Tumularios", tags: ["Humano", "Lanzador", "No muerto", "Esqueleto"], max: 2, cost: 65000, ma: 6, st: 3, ag: 4, pa: 3, av: 9, skills: ["Cabeza dura", "Manos seguras", "Pasar", "Regeneración"], primary: ["G", "P"], secondary: ["A", "F", "T"] },
      { name: "Blitzer de los Reyes Tumularios", tags: ["Humano", "Blitzer", "No muerto", "Esqueleto"], max: 2, cost: 85000, ma: 6, st: 3, ag: 4, pa: 5, av: 9, skills: ["Cabeza dura", "Placar", "Regeneración"], primary: ["F", "G", "M"], secondary: ["A", "T"] },
      { name: "Guardián de Tumbas", tags: ["Humano", "Defensor", "No muerto", "Grandullón"], max: 4, cost: 115000, ma: 4, st: 5, ag: 5, pa: 6, av: 10, skills: ["Descomposición", "Luchador", "Regeneración"], primary: ["F"], secondary: ["A", "G"] },
    ],
  },
  {
    key: "moradores-del-inframundo",
    name: "Moradores del Inframundo",
    pageRef: 186,
    leagues: ["Reto del Inframundo"],
    specialRules: ["Sobornos y Corrupción"],
    rerollCost: 70000,
    rerollMax: 8,
    allowsApothecary: true,
    note: "Puede tener un único jugador Grandullón, a elegir entre Troll o Rata Ogro.",
    positions: [
      { name: "Línea Goblin", tags: ["Goblin", "Línea"], max: 16, cost: 40000, ma: 6, st: 2, ag: 3, pa: 4, av: 8, skills: ["Escurridizo", "Esquivar", "Humanoide bala"], primary: ["A", "M", "T"], secondary: ["G", "F", "P"] },
      { name: "Línea Snotling", tags: ["Snotling", "Línea"], max: 6, cost: 15000, ma: 5, st: 1, ag: 3, pa: 4, av: 6, skills: ["Canijo", "Echarse a un lado", "Escurridizo", "Esquivar", "Humanoide bala", "Insignificante"], primary: ["A", "M", "T"], secondary: ["G"] },
      { name: "Línea Guerrero del clan", tags: ["Skaven", "Línea"], max: 3, cost: 50000, ma: 7, st: 3, ag: 3, pa: 4, av: 8, skills: ["Animosidad (Goblin)"], primary: ["G", "M", "T"], secondary: ["A", "F"] },
      { name: "Lanzador Skaven", tags: ["Skaven", "Lanzador"], max: 1, cost: 80000, ma: 7, st: 3, ag: 3, pa: 2, av: 8, skills: ["Animosidad (Goblin)", "Manos seguras", "Pasar"], primary: ["G", "M", "P"], secondary: ["A", "F", "T"] },
      { name: "Corredor de alcantarilla", tags: ["Skaven", "Corredor"], max: 1, cost: 85000, ma: 9, st: 2, ag: 2, pa: 4, av: 8, skills: ["Animosidad (Goblin)", "Apuñalar", "Esquivar"], primary: ["A", "G", "M", "T"], secondary: ["F"] },
      { name: "Blitzer Skaven", tags: ["Skaven", "Blitzer"], max: 1, cost: 90000, ma: 8, st: 3, ag: 3, pa: 4, av: 9, skills: ["Animosidad (Goblin)", "Placar", "Robar el balón"], primary: ["F", "G", "M"], secondary: ["A", "T"] },
      { name: "Troll", tags: ["Troll", "Grandullón"], max: 1, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10, skills: ["Golpe mortífero", "Lanzar compañero", "Proyectil de vómito", "Realmente estúpido", "Regeneración", "Siempre hambriento", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G", "P"] },
      { name: "Rata Ogro", tags: ["Skaven", "Grandullón"], max: 1, cost: 150000, ma: 6, st: 5, ag: 4, pa: 6, av: 9, skills: ["Cola prensil", "Ferocidad animal", "Furia", "Golpe mortífero", "Solitario (4+)"], primary: ["F", "M"], secondary: ["A", "G"] },
    ],
  },
  {
    key: "vampiros",
    name: "Vampiros",
    pageRef: 187,
    leagues: ["Selectiva de Sylvania"],
    specialRules: ["Señores de los No Muertos"],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Esclavo", tags: ["Humano", "Línea", "Esclavo"], max: 16, cost: 40000, ma: 6, st: 3, ag: 3, pa: 4, av: 8, skills: [], primary: ["G"], secondary: ["A", "F"] },
      { name: "Corredor Vampiro", tags: ["No muerto", "Vampiro", "Corredor"], max: 2, cost: 100000, ma: 8, st: 3, ag: 2, pa: 3, av: 8, skills: ["Mirada hipnótica", "Regeneración", "Sed de sangre (2+)"], primary: ["A", "G"], secondary: ["F", "P"] },
      { name: "Lanzador Vampiro", tags: ["No muerto", "Vampiro", "Lanzador"], max: 2, cost: 110000, ma: 6, st: 4, ag: 2, pa: 2, av: 9, skills: ["Mirada hipnótica", "Pasar", "Regeneración", "Sed de sangre (2+)"], primary: ["A", "G", "P"], secondary: ["F"] },
      { name: "Blitzer Vampiro", tags: ["No muerto", "Vampiro", "Blitzer"], max: 2, cost: 110000, ma: 6, st: 4, ag: 2, pa: 4, av: 9, skills: ["Imparable", "Mirada hipnótica", "Regeneración", "Sed de sangre (3+)"], primary: ["A", "F", "G"], secondary: [] },
      { name: "Vargheist", tags: ["No muerto", "Vampiro", "Grandullón"], max: 1, cost: 150000, ma: 5, st: 5, ag: 4, pa: 6, av: 10, skills: ["Furia", "Garras", "Regeneración", "Sed de sangre (3+)", "Solitario (4+)"], primary: ["G"], secondary: ["A", "G"] },
    ],
  },
  {
    key: "elfos-silvanos",
    name: "Elfos Silvanos",
    pageRef: 188,
    leagues: ["Liga de los Reinos Élficos", "Liga de los Bosques"],
    specialRules: [],
    rerollCost: 60000,
    rerollMax: 8,
    allowsApothecary: true,
    positions: [
      { name: "Línea Elfo silvano", tags: ["Elfo", "Línea"], max: 16, cost: 65000, ma: 7, st: 3, ag: 2, pa: 3, av: 8, skills: [], primary: ["A", "G"], secondary: ["F"] },
      { name: "Lanzador Elfo silvano", tags: ["Elfo", "Lanzador"], max: 2, cost: 85000, ma: 7, st: 3, ag: 2, pa: 2, av: 8, skills: ["Pasar", "Proteger el cuero"], primary: ["A", "G", "P"], secondary: ["F"] },
      { name: "Receptor Elfo silvano", tags: ["Elfo", "Receptor"], max: 2, cost: 90000, ma: 8, st: 2, ag: 2, pa: 3, av: 8, skills: ["Atrapar", "Esprintar", "Esquivar"], primary: ["A", "G"], secondary: ["F", "P"] },
      { name: "Bailarín guerrero", tags: ["Elfo", "Blitzer"], max: 2, cost: 130000, ma: 8, st: 3, ag: 2, pa: 3, av: 8, skills: ["Esquivar", "Placar", "Saltar"], primary: ["A", "G"], secondary: ["F", "P"] },
      { name: "Hombre árbol del bosque Loren", tags: ["Hombre árbol", "Grandullón"], max: 1, cost: 120000, ma: 2, st: 6, ag: 5, pa: 5, av: 11, skills: ["Brazo fuerte", "Cabeza dura", "Echar raíces", "Golpe mortífero", "Lanzar compañero", "Mantenerse firme", "Solitario (4+)"], primary: ["F"], secondary: ["A", "G", "P"] },
    ],
  },
];

