/**
 * Jugadores Estrella oficiales, transcritos del reglamento oficial 2025
 * (BB2025_crap_v1.pdf, págs. 105-...). Validado contra el "STar Players.md"
 * del usuario.
 *
 * Los nombres de habilidad van en español (los resuelve prisma/seedStars.ts
 * contra el catálogo). specialRuleName/Text es la regla única de cada estrella.
 * pa: null = no puede pasar ("–"). playsForAny = "Cualquier equipo".
 */

export interface SeedStar {
  key: string;
  name: string;
  tags: string[];
  cost: number;
  ma: number;
  st: number;
  ag: number;
  pa: number | null;
  av: number;
  skills: string[];
  playsForAny: boolean;
  leagues: string[];
  specialRuleName: string;
  specialRuleText: string;
  /** Debe contratarse en pareja con otra estrella. */
  isPair?: boolean;
}

export const STARS: SeedStar[] = [
  {
    key: "akhorne-la-ardilla", name: "Akhorne La Ardilla", tags: ["Blitzer", "Ardilla"],
    cost: 80000, ma: 7, st: 1, ag: 2, pa: null, av: 6,
    skills: ["Garras", "Agallas", "Esquivar", "Furia", "En pie de un salto", "Solitario (4+)", "El balón ni verlo", "Echarse a un lado", "Escurridizo", "Canijo"],
    playsForAny: true, leagues: [],
    specialRuleName: "Furia ciega",
    specialRuleText: "Akhorne puede elegir volver a tirar el D6 cuando tira la habilidad de Agallas.",
  },
  {
    key: "anqi-panqi", name: "Anqi Panqi", tags: ["Defensor", "Hombre lagarto"],
    cost: 190000, ma: 7, st: 4, ag: 5, pa: 6, av: 10,
    skills: ["Placar", "Apartar", "Solitario (4+)", "Mantenerse firme", "Tembloroso"],
    playsForAny: false, leagues: ["Superliga Lustriana"],
    specialRuleName: "Golpe Salvaje",
    specialRuleText: "Una vez por partida, cuando Anqi realiza una acción de Placaje contra un jugador rival, puede elegir volver a tirar cualquier número de dados de Placaje.",
  },
  {
    key: "barik-farblast", name: "Barik Farblast", tags: ["Enano", "Lanzador"],
    cost: 80000, ma: 6, st: 3, ag: 4, pa: 3, av: 9,
    skills: ["Cañonero", "Pase a lo loco", "Solitario (4+)", "Pasar", "Arma secreta", "Manos seguras", "Cabeza dura"],
    playsForAny: false, leagues: ["Clásica del Viejo Mundo", "Superliga del Fin del Mundo"],
    specialRuleName: "¡Pelotazo!",
    specialRuleText: "Cada vez que Barik hace un Pase a lo loco, puede volver a tirar cualquier resultado de dispersión para determinar dónde cae el balón, y cualquier jugador amigo que intente atrapar el balón gana un modificador adicional de +1 a la tirada.",
  },
  {
    key: "bilerot-vomitflesh", name: "Bilerot Vomitflesh", tags: ["Defensor", "Humano"],
    cost: 180000, ma: 4, st: 5, ag: 4, pa: 6, av: 10,
    skills: ["Jugar sucio", "Presencia perturbadora", "Apariencia asquerosa", "Agresor discreto", "Solitario (4+)", "Regeneración", "Tembloroso"],
    playsForAny: false, leagues: ["Elegidos de Nurgle"],
    specialRuleName: "Regurgitación pútrida",
    specialRuleText: "Una vez por parte, Bilerot puede usar la acción especial Vómito Proyectil. Puede usarse incluso si Bilerot ya ha realizado una acción de bloqueo este turno.",
  },
  {
    key: "the-black-gobbo", name: "The Black Gobbo", tags: ["Goblin", "Especial"],
    cost: 210000, ma: 6, st: 2, ag: 3, pa: 3, av: 8,
    skills: ["Bombardero", "Presencia perturbadora", "Esquivar", "Solitario (3+)", "Echarse a un lado", "Furtivo", "Apuñalar", "Escurridizo"],
    playsForAny: false, leagues: ["Reyerta en las Yermas", "Reto del Inframundo"],
    specialRuleName: "El más astuto de todos",
    specialRuleText: "Si tu equipo incluye al Black Gobbo, puedes cometer dos acciones de falta por turno, siempre que una de las faltas sea cometida por el mismo Black Gobbo.",
  },
  {
    key: "boa-konssstriktr", name: "Boa Kon'ssstriktr", tags: ["Corredor", "Hombre serpiente"],
    cost: 180000, ma: 6, st: 3, ag: 3, pa: 4, av: 9,
    skills: ["Esquivar", "Zafarse", "Mirada hipnótica", "Solitario (4+)", "Cola prensil", "Proteger el cuero", "Echarse a un lado"],
    playsForAny: false, leagues: ["Superliga Lustriana"],
    specialRuleName: "Mira en mis ojos",
    specialRuleText: "Una vez por partido, si Boa comienza su activación marcando a un jugador rival con el balón, puede tirar un D6. Con un 1, no ocurre nada. Con un 2+, el jugador contrario pierde la posesión del balón, Boa gana inmediatamente la posesión del balón, y la activación de Boa termina inmediatamente.",
  },
  {
    key: "bomber-dribblesnot", name: "Bomber Dribblesnot", tags: ["Goblin", "Especial"],
    cost: 80000, ma: 6, st: 2, ag: 3, pa: 3, av: 8,
    skills: ["Precisión", "Bombardero", "Esquivar", "Solitario (4+)", "Humanoide bala", "Arma secreta", "Escurridizo"],
    playsForAny: false, leagues: ["Reyerta en las Yermas", "Reto del Inframundo"],
    specialRuleName: "¡Kaboom!",
    specialRuleText: "Una vez por partida, si un jugador rival atrapa una bomba lanzada por el Bomber, puedes elegir que explote inmediatamente en lugar de tirar para ver si el jugador puede volver a lanzarla.",
  },
  {
    key: "bryce-the-slice-cambuel", name: "Bryce 'The Slice' Cambuel", tags: ["Especial"],
    cost: 130000, ma: 5, st: 3, ag: 4, pa: null, av: 9,
    skills: ["Motosierra", "Solitario (4+)", "Regeneración", "Arma secreta", "Mantenerse firme", "Cabeza dura"],
    playsForAny: false, leagues: ["Selectiva de Sylvania"],
    specialRuleName: "Llamas fantasmales",
    specialRuleText: "Una vez por parte, cuando Bryce hace la acción especial de Ataque con Motosierra como parte de una acción de Penetración, puede añadir +4 a la tirada de Armadura contra el oponente en lugar de +3.",
  },
  {
    key: "capitana-karina-von-riesz", name: "'Capitana' Karina Von Riesz", tags: ["Corredor", "Vampiro"],
    cost: 230000, ma: 7, st: 4, ag: 2, pa: 4, av: 9,
    skills: ["Sed de sangre (2+)", "Esquivar", "Mirada hipnótica", "En pie de un salto", "Solitario (4+)", "Regeneración"],
    playsForAny: false, leagues: ["Selectiva de Sylvania"],
    specialRuleName: "Bocadito Sabroso",
    specialRuleText: "Una vez por partido, cuando Karina falle una tirada de Sed de Sangre, puede elegir morder a un jugador oponente con Fuerza 3 o inferior como si fuera un Siervo de su propio equipo. Karina no puede morder a un Jugador Estrella.",
  },
  {
    key: "conde-luthor-von-drakenborg", name: "Conde Luthor von Drakenborg", tags: ["Defensor", "Vampiro"],
    cost: 300000, ma: 6, st: 5, ag: 2, pa: 3, av: 10,
    skills: ["Placar", "Mirada hipnótica", "Solitario (4+)", "Regeneración", "Echarse a un lado"],
    playsForAny: false, leagues: ["Selectiva de Sylvania"],
    specialRuleName: "Estrella del Show",
    specialRuleText: "Una vez por partido, cuando el Conde Luthor anote un Touchdown, su entrenador puede ganar una Segunda oportunidad de equipo; si no se usa en la siguiente entrada, se pierde.",
  },
  {
    key: "cindy-piewhistle", name: "Cindy Piewhistle", tags: ["Halfling", "Especial"],
    cost: 100000, ma: 5, st: 2, ag: 3, pa: 3, av: 7,
    skills: ["Precisión", "Bombardero", "Esquivar", "Solitario (4+)", "Arma secreta", "Escurridizo"],
    playsForAny: false, leagues: ["Copa Dedal Halfling", "Clásica del Viejo Mundo"],
    specialRuleName: "Todo lo que puedas comer",
    specialRuleText: "Una vez por partida, Cindy puede realizar dos acciones especiales de lanzar bombas en lugar de una, aunque debe indicarlo antes de realizar la primera acción. Si lo hace, inmediatamente después de realizar la segunda acción especial de lanzar bomba tira un D6. Con un 1 a 3, Cindy es expulsada inmediatamente.",
  },
  {
    key: "deeproot-strongbranch", name: "Deeproot Strongbranch", tags: ["Grandullón", "Hombre árbol"],
    cost: 280000, ma: 2, st: 7, ag: 5, pa: 4, av: 11,
    skills: ["Placar", "Ojo de halcón", "Solitario (4+)", "Golpe mortífero", "Mantenerse firme", "Brazo fuerte", "Cabeza dura", "Lanzar compañero", "¡Tronco va!"],
    playsForAny: false, leagues: ["Liga de los Bosques"],
    specialRuleName: "Fiable",
    specialRuleText: "Si Deeproot falla en una acción de lanzar a un compañero, el jugador que iba a ser lanzado rebotará normalmente, pero aterrizará automáticamente de forma segura.",
  },
  {
    key: "dribl", name: "Dribl", tags: ["Eslizón", "Especial"], isPair: true,
    cost: 230000, ma: 8, st: 2, ag: 3, pa: 4, av: 8,
    skills: ["Jugar sucio", "Esquivar", "Solitario (4+)", "Falta rápida", "Echarse a un lado", "Furtivo", "Escurridizo"],
    playsForAny: false, leagues: ["Superliga Lustriana"],
    specialRuleName: "Una pareja furtiva",
    specialRuleText: "Dribl & Drull deben ser contratados como pareja y cuentan como dos jugadores estrella (coste 230k por la pareja). Además, siempre que Dribl o Drull realicen una acción de Puñalada o Falta contra un jugador rival marcado por ambos, pueden aplicar un modificador de +1 a la tirada.",
  },
  {
    key: "drull", name: "Drull", tags: ["Eslizón", "Especial"], isPair: true,
    cost: 230000, ma: 8, st: 2, ag: 3, pa: 4, av: 8,
    skills: ["Esquivar", "Solitario (4+)", "Echarse a un lado", "Apuñalar", "Escurridizo"],
    playsForAny: false, leagues: ["Superliga Lustriana"],
    specialRuleName: "Una pareja furtiva",
    specialRuleText: "Dribl & Drull deben ser contratados como pareja y cuentan como dos jugadores estrella (coste 230k por la pareja). Además, siempre que Dribl o Drull realicen una acción de Puñalada o Falta contra un jugador rival marcado por ambos, pueden aplicar un modificador de +1 a la tirada.",
  },
  {
    key: "eldril-sidewinder", name: "Eldril Sidewinder", tags: ["Receptor", "Elfo"],
    cost: 220000, ma: 8, st: 3, ag: 2, pa: 3, av: 8,
    skills: ["Atrapar", "Esquivar", "Mirada hipnótica", "Solitario (4+)", "Nervios de acero", "Atento al balón"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos"],
    specialRuleName: "Danza hipnótica",
    specialRuleText: "Una vez por mitad, Eldril puede volver a tirar los dados al realizar una acción especial de Mirada hipnótica.",
  },
  {
    key: "estelle-la-veneaux", name: "Estelle La Veneaux", tags: ["Humano", "Línea"],
    cost: 190000, ma: 6, st: 3, ag: 3, pa: 4, av: 8,
    skills: ["Presencia perturbadora", "Esquivar", "Defensa", "Solitario (4+)", "Echarse a un lado"],
    playsForAny: false, leagues: ["Superliga Lustriana"],
    specialRuleName: "Maleficio",
    specialRuleText: "Una vez por partido, al comienzo de la activación de Estelle, elige un jugador del equipo contrario en un radio de cinco casillas y tira un D6. Con un resultado de 2+, el jugador seleccionado se distrae y no puede ser activado durante el siguiente turno de su equipo.",
  },
  {
    key: "frank-n-stein", name: "Frank 'n' Stein", tags: ["Especial"],
    cost: 250000, ma: 4, st: 5, ag: 4, pa: null, av: 10,
    skills: ["Abrirse paso", "Solitario (4+)", "Golpe mortífero (+1)", "Regeneración", "Mantenerse firme", "Cabeza dura"],
    playsForAny: false, leagues: ["Clásica del Viejo Mundo", "Selectiva de Sylvania"],
    specialRuleName: "Placaje brutal",
    specialRuleText: "Una vez por partido, cuando Frank'n'Stein efectúe una tirada de Herida contra un oponente como resultado de un placaje, puede añadir un +1 adicional a la tirada; este modificador puede aplicarse después de hacer la tirada.",
  },
  {
    key: "fungus-the-loon", name: "Fungus the Loon", tags: ["Goblin", "Especial"],
    cost: 80000, ma: 4, st: 7, ag: 3, pa: null, av: 8,
    skills: ["Bola con cadena", "Solitario (4+)", "Golpe mortífero", "El balón ni verlo", "Arma secreta", "Escurridizo"],
    playsForAny: false, leagues: ["Reyerta en las Yermas", "Reto del Inframundo"],
    specialRuleName: "Derviche giratorio",
    specialRuleText: "Una vez por activación, Fungus puede volver a tirar el D6 al determinar en qué dirección se mueve.",
  },
  {
    key: "glart-smashrip", name: "Glart Smashrip", tags: ["Defensor", "Skaven"],
    cost: 175000, ma: 5, st: 4, ag: 4, pa: 6, av: 9,
    skills: ["Placar", "Garras", "Apartar", "Imparable", "Solitario (4+)", "Mantenerse firme"],
    playsForAny: false, leagues: ["Reto del Inframundo"],
    specialRuleName: "Carrera frenética",
    specialRuleText: "Una vez por partido, cuando Glart realiza una acción Blitz, puede ganar la habilidad Furia. Debes declarar que esta regla especial se usa cuando Glart es activado. Glart no puede usar la habilidad de Apartar durante el turno en el que use esta regla especial.",
  },
  {
    key: "gloriel-summerbloom", name: "Gloriel Summerbloom", tags: ["Elfo", "Lanzador"],
    cost: 150000, ma: 7, st: 2, ag: 2, pa: 2, av: 8,
    skills: ["Precisión", "Esquivar", "Solitario (3+)", "Pasar", "Echarse a un lado", "Manos seguras"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos"],
    specialRuleName: "Disparo a la nada",
    specialRuleText: "Una vez por partido, cuando Gloriel realiza una acción de pase, puede ganar la habilidad de Pase a lo loco. Debes declarar que esta regla especial se usa en el momento que Gloriel es activado.",
  },
  {
    key: "glotl-stop", name: "Glotl Stop", tags: ["Grandullón", "Hombre lagarto"],
    cost: 260000, ma: 6, st: 6, ag: 5, pa: 6, av: 10,
    skills: ["Ferocidad animal", "Furia", "Solitario (4+)", "Golpe mortífero", "Cola prensil", "Mantenerse firme", "Cabeza dura"],
    playsForAny: false, leagues: ["Superliga Lustriana"],
    specialRuleName: "Salvajismo primitivo",
    specialRuleText: "Una vez por partido, cuando Glotl falla una tirada de Ferocidad animal, puede golpear contra un jugador rival en lugar de contra un compañero.",
  },
  {
    key: "grak", name: "Grak", tags: ["Grandullón", "Ogro"], isPair: true,
    cost: 250000, ma: 5, st: 5, ag: 4, pa: 4, av: 10,
    skills: ["Estúpido", "Chutar compañero", "Solitario (4+)", "Golpe mortífero", "Cabeza dura"],
    playsForAny: true, leagues: [],
    specialRuleName: "Te llevaré",
    specialRuleText: "Grak y Crumbleberry deben ser contratados como pareja (coste 250k por la pareja). Además, mientras Crumbleberry es transportado por Grak, este último obtiene las habilidades Abrirse paso y Esquivar.",
  },
  {
    key: "crumbleberry", name: "Crumbleberry", tags: ["Halfling", "Línea"], isPair: true,
    cost: 250000, ma: 5, st: 2, ag: 3, pa: 5, av: 7,
    skills: ["Esquivar", "Vuelo letal", "Solitario (4+)", "Humanoide bala", "Escurridizo", "Manos seguras"],
    playsForAny: true, leagues: [],
    specialRuleName: "Te llevaré",
    specialRuleText: "Grak y Crumbleberry deben ser contratados como pareja (coste 250k por la pareja). Además, mientras Crumbleberry es transportado por Grak, este último obtiene las habilidades Abrirse paso y Esquivar.",
  },
  {
    key: "grashnak-pezunanegra", name: "Grashnak Pezuñanegra", tags: ["Grandullón", "Minotauro"],
    cost: 240000, ma: 6, st: 6, ag: 4, pa: 6, av: 9,
    skills: ["Furia", "Cuernos", "Solitario (4+)", "Golpe mortífero", "Cabeza dura", "Ira descontrolada"],
    playsForAny: false, leagues: ["Competición del Caos"],
    specialRuleName: "Corneado por el toro",
    specialRuleText: "Una vez por partida, cuando Grashnak realiza una acción de penetración, puede tirar un dado de placaje adicional contra el jugador contrario, independientemente de la Fuerza de este, hasta un máximo de tres dados de placaje. Si Grashnak realiza una segunda acción de placaje debido a la habilidad Furia, esta también se beneficiará de esta regla.",
  },
  {
    key: "gretchen-wachter", name: "Gretchen Wachter \"La Viuda del Blood Bowl\"", tags: ["Especial", "No muerto", "Espectro"],
    cost: 180000, ma: 7, st: 3, ag: 2, pa: null, av: 9,
    skills: ["Presencia perturbadora", "Esquivar", "Apariencia asquerosa", "En pie de un salto", "Solitario (4+)", "El balón ni verlo", "Regeneración", "Perseguir", "Echarse a un lado"],
    playsForAny: false, leagues: ["Selectiva de Sylvania"],
    specialRuleName: "Incorpórea",
    specialRuleText: "Una vez por partida, cuando Gretchen se activa, puede usar esta regla especial. Hasta el final de su activación, Gretchen no tiene que realizar tiradas de Esquivar por abandonar una casilla dentro de la Zona de placaje de un jugador contrario.",
  },
  {
    key: "griff-oberwald", name: "Griff Oberwald", tags: ["Blitzer", "Humano"],
    cost: 300000, ma: 7, st: 4, ag: 2, pa: 3, av: 9,
    skills: ["Placar", "Esquivar", "Zafarse", "Solitario (3+)", "Esprintar", "Pies firmes"],
    playsForAny: false, leagues: ["Clásica del Viejo Mundo"],
    specialRuleName: "Profesional consumado",
    specialRuleText: "Una vez por partida, Griff puede aplicar un modificador de +1 a una tirada de agilidad que haya realizado. Este modificador se puede aplicar después de haber realizado la tirada.",
  },
  {
    key: "grim-ironjaw", name: "Grim Ironjaw", tags: ["Enano", "Especial"],
    cost: 200000, ma: 5, st: 4, ag: 3, pa: 6, av: 9,
    skills: ["Placar", "Agallas", "Furia", "Odio (Grandullón)", "Solitario (4+)", "Placaje múltiple", "Cabeza dura"],
    playsForAny: false, leagues: ["Superliga del Fin del Mundo"],
    specialRuleName: "Matador",
    specialRuleText: "Una vez por partido, cuando un jugador Big Guy oponente con Fuerza de 5 o más es derribado como resultado de una acción de placaje realizada por Grim, puedes aplicar un modificador adicional +1 a la tirada de Armadura o a la de Herida. Puede aplicarse después de hacer la tirada.",
  },
  {
    key: "grombrindal", name: "Grombrindal, el Enano Blanco", tags: ["Defensor", "Enano"],
    cost: 170000, ma: 5, st: 3, ag: 3, pa: 4, av: 10,
    skills: ["Placar", "Abrirse paso", "Agallas", "Solitario (4+)", "Golpe mortífero", "Mantenerse firme", "Pies firmes", "Cabeza dura"],
    playsForAny: false, leagues: ["Copa Dedal Halfling", "Clásica del Viejo Mundo", "Superliga del Fin del Mundo"],
    specialRuleName: "Sabiduría del Enano Blanco",
    specialRuleText: "Una vez por partida, cuando se active Grombrindal, puede seleccionar a un compañero a 2 casillas. El compañero obtiene una de estas habilidades hasta el final del turno: Placaje defensivo, Agallas, Golpe mortífero o Pies firmes.",
  },
  {
    key: "guffle-pusmaw", name: "Guffle Pusmaw", tags: ["Defensor", "Humano"],
    cost: 150000, ma: 5, st: 4, ag: 4, pa: 6, av: 10,
    skills: ["Apariencia asquerosa", "Solitario (4+)", "Boca monstruosa", "Nervios de acero", "Atento al balón", "Infectado"],
    playsForAny: false, leagues: ["Elegidos de Nurgle"],
    specialRuleName: "Mordisco rápido",
    specialRuleText: "Una vez por partido, si Guffle está marcando a un jugador contrario que atrapa el balón, puede hacer inmediatamente una tirada de Armadura sin modificadores (y la de Herida si procede) contra ese jugador. Si supera la armadura, Guffle obtiene inmediatamente la posesión del balón. No provoca pérdida de turno.",
  },
  {
    key: "hthark-el-imparable", name: "H'thark el Imparable", tags: ["Blitzer", "Enano"],
    cost: 300000, ma: 6, st: 6, ag: 4, pa: 6, av: 10,
    skills: ["Placar", "Abrirse paso", "Romper defensas", "Imparable", "Solitario (4+)", "Esprintar", "Pies firmes", "Cabeza dura"],
    playsForAny: false, leagues: ["Reyerta en las Yermas", "Elegidos de Hashut"],
    specialRuleName: "Momento imparable",
    specialRuleText: "Cuando H'Thark realice una acción de blitz, puede repetir un solo dado de placaje.",
  },
  {
    key: "hakflem-skuttlespike", name: "Hakflem Skuttlespike", tags: ["Corredor", "Skaven"],
    cost: 200000, ma: 8, st: 3, ag: 2, pa: 3, av: 8,
    skills: ["Esquivar", "Brazos adicionales", "Solitario (4+)", "Cola prensil", "Dos cabezas"],
    playsForAny: false, leagues: ["Reto del Inframundo"],
    specialRuleName: "Traicionero",
    specialRuleText: "Una vez por partido, si un compañero adyacente a Hakflem está en posesión del balón cuando Hakflem se activa, ese jugador puede ser derribado inmediatamente y Hakflem toma posesión del balón. No se produce cambio de turno por el uso de esta regla.",
  },
  {
    key: "helmut-wolf", name: "Helmut Wolf", tags: ["Humano", "Especial"],
    cost: 140000, ma: 6, st: 3, ag: 3, pa: null, av: 9,
    skills: ["Motosierra", "Solitario (4+)", "El balón ni verlo", "Profesional", "Arma secreta", "Mantenerse firme"],
    playsForAny: false, leagues: ["Clásica del Viejo Mundo"],
    specialRuleName: "Viejo profesional",
    specialRuleText: "Una vez por partido, Helmut puede usar su habilidad Profesional para repetir un solo dado de la tirada de Armadura.",
  },
  {
    key: "ivan-deathshroud", name: "Ivan 'el Animal' Deathshroud", tags: ["Blitzer", "Humano", "Esqueleto", "No muerto"],
    cost: 210000, ma: 6, st: 4, ag: 4, pa: 5, av: 9,
    skills: ["Placar", "Presencia perturbadora", "Odio (Enano)", "Imparable", "Solitario (4+)", "Regeneración", "Robar el balón", "Placaje defensivo"],
    playsForAny: false, leagues: ["Selectiva de Sylvania"],
    specialRuleName: "Azote de los enanos",
    specialRuleText: "Una vez por partido, cuando un oponente es derribado por un Placaje o Blitz de Ivan, puedes aplicar un +1 a la tirada de Armadura o de Heridas; si el jugador derribado es un enano de cualquier equipo, aplica en su lugar un +2.",
  },
  {
    key: "ivar-eriksson", name: "Ivar Eriksson", tags: ["Blitzer", "Humano"],
    cost: 215000, ma: 6, st: 4, ag: 3, pa: 4, av: 9,
    skills: ["Placar", "Defensa", "Solitario (3+)", "Placaje defensivo"],
    playsForAny: false, leagues: ["Clásica del Viejo Mundo"],
    specialRuleName: "Grupo de asalto",
    specialRuleText: "Una vez por parte, siempre que Ivar comience su activación, puede elegir un jugador abierto de su equipo en un radio de cinco casillas. El jugador elegido puede mover inmediatamente una casilla, ignorando las zonas de defensa, aunque debe terminar este movimiento marcando a un jugador contrario.",
  },
  {
    key: "jeremiah-kool", name: "Jeremiah Kool", tags: ["Elfo", "Corredor"],
    cost: 300000, ma: 8, st: 3, ag: 1, pa: 2, av: 9,
    skills: ["Placar", "Esquivar", "Recepción heroica", "Pase precipitado", "Solitario (4+)", "Nervios de acero", "Atento al balón", "Pasar", "Echarse a un lado"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos"],
    specialRuleName: "La Hoja Destellante",
    specialRuleText: "Una vez por partida, al comienzo de su activación, Jeremiah puede declarar una Acción de Puñalada contra un jugador contrario al que está Marcando. Después de realizar la Acción Especial de Puñalada, Jeremiah puede realizar una Acción de Movimiento antes de que termine su activación.",
  },
  {
    key: "jordell-freshbreeze", name: "Jordell Freshbreeze", tags: ["Blitzer", "Elfo"],
    cost: 280000, ma: 8, st: 3, ag: 1, pa: 3, av: 8,
    skills: ["Placar", "Recepción heroica", "Esquivar", "Saltar", "Solitario (4+)", "Echarse a un lado", "Equilibrio firme"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos"],
    specialRuleName: "Veloz como la brisa",
    specialRuleText: "Una vez por partida, Jordell puede elegir superar una única tirada de Esquivar, Saltar o Forzar la marcha con un 2+, independientemente de cualquier modificador.",
  },
  {
    key: "josef-bugman", name: "Josef Bugman", tags: ["Defensor", "Enano"],
    cost: 180000, ma: 5, st: 3, ag: 3, pa: 4, av: 9,
    skills: ["Placar", "Borracho", "Zafarse", "Solitario (3+)", "Placaje defensivo", "Provocar", "Cabeza dura"],
    playsForAny: false, leagues: ["Clásica del Viejo Mundo", "Superliga del Fin del Mundo"],
    specialRuleName: "Determinación enana",
    specialRuleText: "Una vez por partida, cuando la armadura de Josef se rompa como resultado de una tirada de armadura, puedes elegir que se vuelva a tirar la tirada de armadura.",
  },
  {
    key: "karla-von-kill", name: "Karla Von Kill", tags: ["Blitzer", "Humano"],
    cost: 210000, ma: 6, st: 4, ag: 3, pa: 3, av: 9,
    skills: ["Placar", "Agallas", "Esquivar", "En pie de un salto", "Solitario (4+)"],
    playsForAny: false, leagues: ["Superliga Lustriana", "Clásica del Viejo Mundo"],
    specialRuleName: "Indomable",
    specialRuleText: "Una vez por partido, cuando Karla tira con éxito para usar su habilidad Agallas, puede aumentar su característica de Fuerza para doblar la del objetivo elegido en su acción de placaje.",
  },
  {
    key: "kiroth-krakeneye", name: "Kiroth Krakeneye", tags: ["Elfo", "Corredor"],
    cost: 160000, ma: 7, st: 3, ag: 2, pa: 3, av: 8,
    skills: ["Presencia perturbadora", "Apariencia asquerosa", "Solitario (4+)", "Atento al balón", "Placaje defensivo", "Tentáculos"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos"],
    specialRuleName: "Tinta negra",
    specialRuleText: "Una vez por partida, al inicio de cualquiera de sus activaciones, Kiroth puede elegir a un jugador rival al que está marcando. El jugador elegido pierde su Zona de defensa hasta su siguiente reactivación.",
  },
  {
    key: "kreek-rustgouger", name: "Kreek Rustgouger", tags: ["Grandullón", "Skaven", "Especial"],
    cost: 180000, ma: 5, st: 7, ag: 4, pa: null, av: 10,
    skills: ["Bola con cadena", "Solitario (4+)", "Golpe mortífero", "El balón ni verlo", "Cola prensil", "Arma secreta"],
    playsForAny: false, leagues: ["Reto del Inframundo"],
    specialRuleName: "Volveré",
    specialRuleText: "La primera vez que Kreek es expulsado en la partida debido a su arma secreta, no es expulsado y en su lugar puede continuar como parte del juego.",
  },
  {
    key: "lord-borak", name: "Lord Borak El Saqueador", tags: ["Defensor", "Humano"],
    cost: 270000, ma: 5, st: 5, ag: 3, pa: 5, av: 10,
    skills: ["Placar", "Jugar sucio", "Líder", "Solitario (3+)", "Golpe mortífero", "Meter la bota", "Furtivo"],
    playsForAny: false, leagues: ["Competición del Caos"],
    specialRuleName: "Señor del Caos",
    specialRuleText: "Una vez por partida, cuando Lord Borak realice una acción de placaje, podrá volver a tirar un solo dado de placaje.",
  },
  {
    key: "maple-highgrove", name: "Maple Highgrove", tags: ["Grandullón", "Hombre árbol"],
    cost: 210000, ma: 3, st: 5, ag: 5, pa: 5, av: 11,
    skills: ["Luchador", "Apartar", "Solitario (4+)", "Golpe mortífero", "Mantenerse firme", "Tentáculos", "Cabeza dura"],
    playsForAny: false, leagues: ["Liga de los Bosques"],
    specialRuleName: "Enredaderas Viciosas",
    specialRuleText: "Una vez por mitad, cuando Maple declara una acción de Bloqueo puede hacerlo contra un jugador contrario que esté a 2 casillas de distancia siguiendo todas las reglas normales, aunque no puede seguirlo. Esta acción de Placaje no puede formar parte de una acción de Penetración.",
  },
  {
    key: "max-spleenripper", name: "Max Spleenripper", tags: ["Humano", "Especial"],
    cost: 130000, ma: 5, st: 4, ag: 4, pa: null, av: 9,
    skills: ["Motosierra", "Solitario (4+)", "El balón ni verlo", "Arma secreta"],
    playsForAny: false, leagues: ["Elegidos de Khorne"],
    specialRuleName: "Carnicería máxima",
    specialRuleText: "Una vez por partida, después de que Max realice una acción especial de ataque con motosierra, puede realizar inmediatamente otra acción especial de ataque con motosierra que tenga como objetivo a otro jugador rival.",
  },
  {
    key: "mighty-zug", name: "Mighty Zug", tags: ["Defensor", "Humano"],
    cost: 220000, ma: 5, st: 5, ag: 4, pa: 6, av: 10,
    skills: ["Placar", "Solitario (4+)", "Golpe mortífero"],
    playsForAny: false, leagues: ["Superliga Lustriana", "Clásica del Viejo Mundo"],
    specialRuleName: "Golpe de aplastamiento",
    specialRuleText: "Una vez por partida, cuando un jugador oponente es derribado como resultado de una acción de bloqueo realizada por Zug, puedes aplicar un modificador adicional +1 a la tirada de Armadura. Puede aplicarse después de hacer la tirada.",
  },
  {
    key: "morg-n-thorg", name: "Morg 'n' Thorg", tags: ["Grandullón", "Ogro"],
    cost: 340000, ma: 6, st: 6, ag: 3, pa: 4, av: 11,
    skills: ["Placar", "Ojo de halcón", "Odio (No muerto)", "Solitario (4+)", "Golpe mortífero", "Cabeza dura", "Lanzar compañero"],
    playsForAny: true, leagues: [],
    specialRuleName: "La Ballesta",
    specialRuleText: "Puede jugar para cualquier equipo excepto Selectiva de Sylvania (coste 340k; 380k en algunas ligas). Una vez por partido, si Morg falla el chequeo de Pase al hacer una acción de Pasar o de Lanzar compañero, puede volver a tirar el D6.",
  },
  {
    key: "nobbla-blackwart", name: "Nobbla Blackwart", tags: ["Goblin", "Especial"],
    cost: 120000, ma: 6, st: 2, ag: 3, pa: null, av: 8,
    skills: ["Placar", "Motosierra", "Esquivar", "Solitario (4+)", "El balón ni verlo", "Arma secreta", "Escurridizo"],
    playsForAny: false, leagues: ["Reyerta en las Yermas", "Reto del Inframundo"],
    specialRuleName: "¡Patéalos mientras están en el suelo!",
    specialRuleText: "Una vez por partida, Nobbla puede usar la acción especial Ataque con Motosierra contra un jugador contrario que esté Tumbado o Aturdido. Esto no cuenta como una acción de falta, por lo que Nobbla no puede ser expulsado al usar esta habilidad.",
  },
  {
    key: "puggy-baconbreath", name: "Puggy Baconbreath", tags: ["Blitzer", "Halfling"],
    cost: 120000, ma: 5, st: 3, ag: 3, pa: 3, av: 8,
    skills: ["Placar", "Esquivar", "Solitario (3+)", "Nervios de acero", "Humanoide bala", "Escurridizo"],
    playsForAny: false, leagues: ["Copa Dedal Halfling", "Clásica del Viejo Mundo"],
    specialRuleName: "La suerte del halfling",
    specialRuleText: "Una vez por partida, Puggy puede volver a tirar un dado que haya sido lanzado como un solo dado, como parte de una tirada múltiple o de una reserva de dados (no puede ser un dado de una tirada de Armadura, Herida o Bajas).",
  },
  {
    key: "rashnak-backstabber", name: "Rashnak Backstabber", tags: ["Goblin", "Especial"],
    cost: 130000, ma: 7, st: 3, ag: 3, pa: 5, av: 8,
    skills: ["Solitario (4+)", "Perseguir", "Echarse a un lado", "Furtivo", "Apuñalar"],
    playsForAny: false, leagues: ["Reyerta en las Yermas"],
    specialRuleName: "Conocedor de Toxinas",
    specialRuleText: "Una vez por partido, cuando Rashnak supere con éxito la armadura de un jugador rival como resultado de una acción especial de Apuñalar, puedes aplicar un modificador adicional de +1 a la tirada de Herida. Puede aplicarse después de hacer la tirada.",
  },
  {
    key: "ripper-bolgrot", name: "Ripper Bolgrot", tags: ["Grandullón", "Troll"],
    cost: 250000, ma: 5, st: 6, ag: 5, pa: 4, av: 10,
    skills: ["Ojo de halcón", "Apartar", "Solitario (4+)", "Golpe mortífero", "Regeneración", "Lanzar compañero"],
    playsForAny: false, leagues: ["Reyerta en las Yermas", "Reto del Inframundo"],
    specialRuleName: "Troll del hombre pensante",
    specialRuleText: "Una vez por parte, Ripper puede volver a tirar un dado que haya sido lanzado como un solo dado, como parte de una tirada múltiple o de un grupo de dados (no puede ser un dado de una tirada de Armadura, Herida o Bajas).",
  },
  {
    key: "rodney-roachbait", name: "Rodney Roachbait", tags: ["Gnomo", "Especial"],
    cost: 70000, ma: 6, st: 2, ag: 3, pa: 4, av: 7,
    skills: ["Atrapar", "Recepción heroica", "En pie de un salto", "Solitario (4+)", "Atento al balón", "Echarse a un lado", "Escurridizo", "Forcejear"],
    playsForAny: false, leagues: ["Liga de los Bosques"],
    specialRuleName: "Captura del día",
    specialRuleText: "Una vez por mitad, si Rodney está de pie y comienza su activación a menos de 3 casillas de un balón que está en el suelo, puede tirar un D6. Con un 1-2, no pasa nada. Con un 3+, Rodney obtiene inmediatamente la posesión del balón.",
  },
  {
    key: "rowana-forestfoot", name: "Rowana Forestfoot", tags: ["Defensor", "Gnomo"],
    cost: 160000, ma: 6, st: 3, ag: 3, pa: 4, av: 8,
    skills: ["Esquivar", "Pase precipitado", "Defensa", "Cuernos", "En pie de un salto", "Saltar", "Solitario (4+)"],
    playsForAny: false, leagues: ["Liga de los Bosques"],
    specialRuleName: "Salto Inalterable",
    specialRuleText: "Una vez por partida, después de declarar que va a saltar pero antes de tirar ningún dado, Rowana puede elegir utilizar esta regla especial. Si lo hace, Rowana no sufre modificadores negativos en la prueba de Agilidad para Saltar y puede elegir repetir el resultado.",
  },
  {
    key: "roxanna-darknail", name: "Roxanna Darknail", tags: ["Elfo", "Especial"],
    cost: 270000, ma: 8, st: 3, ag: 1, pa: 3, av: 8,
    skills: ["Esquivar", "Furia", "En pie de un salto", "Imparable", "Saltar", "Solitario (4+)"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos"],
    specialRuleName: "Uñas afiladas",
    specialRuleText: "Una vez por mitad, cuando Roxanna declara una acción de Penetración, obtiene la habilidad Garras hasta el final de su activación.",
  },
  {
    key: "rumbelow-sheepskin", name: "Rumbelow Sheepskin", tags: ["Blitzer", "Halfling"],
    cost: 170000, ma: 6, st: 3, ag: 3, pa: 5, av: 8,
    skills: ["Placar", "Cuernos", "Imparable", "Solitario (4+)", "Placaje defensivo", "Cabeza dura"],
    playsForAny: false, leagues: ["Copa Dedal Halfling"],
    specialRuleName: "Carnero",
    specialRuleText: "Una vez por partido, cuando un jugador oponente es derribado como resultado de una acción de placaje realizada por Rumbelow, puedes aplicar un modificador adicional +1 a la tirada de Armadura o a la de Herida. Puede aplicarse después de hacer la tirada.",
  },
  {
    key: "scrappa-sorehead", name: "Scrappa Sorehead", tags: ["Goblin", "Especial"],
    cost: 120000, ma: 7, st: 2, ag: 3, pa: 4, av: 8,
    skills: ["Jugar sucio", "Esquivar", "Solitario (4+)", "Pogo saltarín", "Humanoide bala", "Esprintar", "Escurridizo", "Pies firmes"],
    playsForAny: false, leagues: ["Reyerta en las Yermas", "Reto del Inframundo"],
    specialRuleName: "¡Yoink!",
    specialRuleText: "Una vez por partida, cuando Scrappa intenta interferir en una acción de pase, puede tirar un D6. Con un 2+, no necesita tirar para interferir, sino que automáticamente hace una intercepción y gana el control del balón.",
  },
  {
    key: "scyla-anfingrimm", name: "Scyla Anfingrimm", tags: ["Grandullón", "Engendro"],
    cost: 200000, ma: 5, st: 5, ag: 4, pa: 6, av: 10,
    skills: ["Garras", "Furia", "Solitario (4+)", "Golpe mortífero", "Cola prensil", "Cabeza dura", "Ira descontrolada"],
    playsForAny: false, leagues: ["Elegidos de Khorne"],
    specialRuleName: "Furia del Dios de la Sangre",
    specialRuleText: "Una vez por partida, si Scyla obtiene un 1 en su tirada de Ira descontrolada tras declarar una Acción de Placar, en lugar de los efectos habituales puede realizar dos Acciones de Placar. La primera debe resolverse por completo, incluido el uso de Furia, antes de realizar la segunda.",
  },
  {
    key: "skitter-stab-stab", name: "Skitter Apuñalar-Apuñalar", tags: ["Corredor", "Skaven"],
    cost: 170000, ma: 9, st: 2, ag: 2, pa: 4, av: 8,
    skills: ["Esquivar", "Solitario (4+)", "Cola prensil", "Perseguir", "Apuñalar"],
    playsForAny: false, leagues: ["Reto del Inframundo"],
    specialRuleName: "Maestro asesino",
    specialRuleText: "Una vez por partido, cuando Skitter supera la tirada de armadura de un rival como resultado de una acción especial de Apuñalar, puede elegir repetir la tirada de Armadura.",
  },
  {
    key: "skrorg-snowpelt", name: "Skrorg Snowpelt", tags: ["Grandullón", "Yeti"],
    cost: 240000, ma: 5, st: 5, ag: 4, pa: 6, av: 9,
    skills: ["Placar", "Garras", "Presencia perturbadora", "Imparable", "Solitario (4+)", "Golpe mortífero"],
    playsForAny: false, leagues: ["Clásica del Viejo Mundo", "Superliga del Fin del Mundo"],
    specialRuleName: "Inflar a la multitud",
    specialRuleText: "Una vez por partido, cuando Skrorg hace que un jugador del equipo contrario sea eliminado como baja por una acción de bloqueo, su entrenador gana una segunda oportunidad de equipo. Si no se usa al final de la parte, se pierde.",
  },
  {
    key: "skrull-halfheight", name: "Skrull Halfheight", tags: ["Enano", "Esqueleto", "Lanzador", "No muerto"],
    cost: 150000, ma: 6, st: 3, ag: 4, pa: 3, av: 9,
    skills: ["Precisión", "Solitario (4+)", "Nervios de acero", "Pasar", "Regeneración", "Manos seguras", "Cabeza dura"],
    playsForAny: false, leagues: ["Selectiva de Sylvania", "Superliga del Fin del Mundo"],
    specialRuleName: "Fuerte juego de pases",
    specialRuleText: "Una vez por partido, después de hacer una tirada de habilidad de pase para realizar un pase, Skrull puede elegir modificar la tirada añadiendo su característica de Fuerza hasta un máximo de 6.",
  },
  {
    key: "lucian-swift", name: "Lucian Swift", tags: ["Blitzer", "Elfo"], isPair: true,
    cost: 300000, ma: 7, st: 3, ag: 2, pa: 3, av: 9,
    skills: ["Placar", "Solitario (4+)", "Golpe mortífero", "Placaje defensivo"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos"],
    specialRuleName: "Trabajando en tándem",
    specialRuleText: "Los gemelos Swift deben ser contratados como pareja (coste 300k por la pareja). Además, si Valen realiza una acción de pase que rodea una casilla que contiene a Lucian, Valen no sufre modificadores en la tirada de PA por el alcance de la acción de pase.",
  },
  {
    key: "valen-swift", name: "Valen Swift", tags: ["Elfo", "Lanzador"], isPair: true,
    cost: 300000, ma: 7, st: 3, ag: 2, pa: 2, av: 9,
    skills: ["Precisión", "Solitario (4+)", "Nervios de acero", "Pasar", "Pase seguro", "Manos seguras"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos"],
    specialRuleName: "Trabajando en tándem",
    specialRuleText: "Los gemelos Swift deben ser contratados como pareja (coste 300k por la pareja). Además, si Valen realiza una acción de pase que rodea una casilla que contiene a Lucian, Valen no sufre modificadores en la tirada de PA por el alcance de la acción de pase.",
  },
  {
    key: "swiftvine-glimmershard", name: "Swiftvine Glimmershard", tags: ["Especial", "Hada"],
    cost: 110000, ma: 7, st: 2, ag: 3, pa: 5, av: 7,
    skills: ["Presencia perturbadora", "Zafarse", "Solitario (4+)", "Echarse a un lado", "Apuñalar", "Escurridizo"],
    playsForAny: false, leagues: ["Liga de los Bosques"],
    specialRuleName: "Estallido Furioso",
    specialRuleText: "Una vez por mitad, si está de pie al inicio de la activación, Swiftvine puede colocarse adyacente a un jugador rival de pie en un radio de 3 casillas e inmediatamente realizar una acción especial de puñalada contra él. Luego puede recolocarse en una casilla desocupada en un radio de 3 casillas desde su nueva posición. Su activación finaliza. Esto cuenta como la acción de Penetración del equipo para el turno.",
  },
  {
    key: "thorsson-stoutmead", name: "Thorsson Stoutmead", tags: ["Humano", "Línea"],
    cost: 170000, ma: 6, st: 3, ag: 4, pa: 3, av: 8,
    skills: ["Placar", "Borracho", "Solitario (4+)", "Cabeza dura"],
    playsForAny: false, leagues: ["Clásica del Viejo Mundo", "Superliga del Fin del Mundo"],
    specialRuleName: "¡Asalto de barril de cerveza!",
    specialRuleText: "Una vez por turno, al comienzo de su activación, Thorsson puede seleccionar a un jugador contrario dentro de tres casillas y tirar un D6. Con un 3+, el jugador seleccionado queda derribado. Con un 2, no ocurre nada. Con un 1, Thorsson se cae. Tras usar esta regla, su activación termina inmediatamente.",
  },
  {
    key: "varag-ghoul-chewer", name: "Varag Ghoul-Chewer", tags: ["Defensor", "Orco"],
    cost: 260000, ma: 6, st: 5, ag: 3, pa: 5, av: 10,
    skills: ["Placar", "Odio (No muerto)", "En pie de un salto", "Solitario (4+)", "Golpe mortífero", "Cabeza dura", "Tembloroso"],
    playsForAny: false, leagues: ["Reyerta en las Yermas"],
    specialRuleName: "Krump and Smash",
    specialRuleText: "Una vez por partida, cuando un jugador contrario sea derribado como resultado de una acción de bloqueo realizada por Varag, puede volver a tirar la tirada de armadura.",
  },
  {
    key: "wilhelm-chaney", name: "Wilhelm Chaney", tags: ["Blitzer", "No muerto", "Hombre lobo"],
    cost: 220000, ma: 8, st: 4, ag: 3, pa: 4, av: 9,
    skills: ["Atrapar", "Garras", "Furia", "Solitario (4+)", "Regeneración", "Forcejear"],
    playsForAny: false, leagues: ["Selectiva de Sylvania"],
    specialRuleName: "Aullido salvaje",
    specialRuleText: "Una vez por partido, cuando Wilhelm hace una tirada de lesión contra un jugador contrario, puede elegir volver a tirar el resultado.",
  },
  {
    key: "willow-rosebark", name: "Willow Rosebark", tags: ["Blitzer", "Dríada"],
    cost: 160000, ma: 6, st: 4, ag: 3, pa: 5, av: 9,
    skills: ["Agallas", "Solitario (4+)", "Echarse a un lado", "Cabeza dura"],
    playsForAny: false, leagues: ["Liga de los Bosques"],
    specialRuleName: "Furia del bosque",
    specialRuleText: "Una vez por partido, cuando Willow realiza una acción de placaje que provocaría que fuera derribada, puede elegir volver a tirar un solo dado de placaje.",
  },
  {
    key: "withergrasp-doubledrool", name: "Withergrasp Doubledrool", tags: ["Hombre bestia", "Defensor"],
    cost: 170000, ma: 6, st: 3, ag: 3, pa: 4, av: 9,
    skills: ["Apariencia asquerosa", "Solitario (4+)", "Cola prensil", "Placaje defensivo", "Tentáculos", "Dos cabezas", "Forcejear"],
    playsForAny: false, leagues: ["Elegidos de Nurgle"],
    specialRuleName: "¡Cuidado!",
    specialRuleText: "La primera vez en cada mitad que Withergrasp sea el objetivo de una acción de Bloqueo de un jugador contrario, cuenta como si tuviera la habilidad de Esquivar.",
  },
  {
    key: "zolcath-the-zoat", name: "Zolcath the Zoat", tags: ["Grandullón", "Zoat"],
    cost: 220000, ma: 5, st: 5, ag: 4, pa: 5, av: 10,
    skills: ["Presencia perturbadora", "Imparable", "Solitario (4+)", "Golpe mortífero", "Cola prensil", "Regeneración", "Pies firmes"],
    playsForAny: false, leagues: ["Liga de los Reinos Élficos", "Superliga Lustriana"],
    specialRuleName: "¿Disculpa, eres un Zoat?",
    specialRuleText: "Una vez por partido, cuando se activa Zolcath, puede seleccionar a un jugador contrario a una distancia máxima de 3 casillas. El jugador seleccionado pierde inmediatamente su Zona de placaje hasta que se active de nuevo.",
  },
  {
    key: "zzharg-madeye", name: "Zzharg Madeye", tags: ["Enano", "Especial"],
    cost: 130000, ma: 4, st: 4, ag: 4, pa: 3, av: 10,
    skills: ["Cañonero", "Pase a lo loco", "Solitario (4+)", "Nervios de acero", "Arma secreta", "Cabeza dura"],
    playsForAny: false, leagues: ["Elegidos de Hashut"],
    specialRuleName: "Las explosiones lo resuelven todo",
    specialRuleText: "Una vez por parte, al inicio de su activación, Zzharg puede realizar una acción especial de Explosión de Trabuco: selecciona a un jugador rival en pie en un radio de 3 casillas y tira un D6. Con un 3+ es alcanzado (tirada de Armadura no modificada, y de Herida si procede). Con un 2, el entrenador contrario elige otro jugador en radio de 3 casillas para ser golpeado. Con un 1, Zzharg recibe el impacto. Su activación finaliza inmediatamente.",
  },
];
